### PR TITLE
New app: Sun and Moon

### PR DESCRIPTION
**Pull request by bboatwright**
# Description
Displays Sun and Moon rise and set times for user's location with option to toggle between 12-hr and 24-hr display.

# Copilot

copilot:all

### CODE REVIEW

**Comment by bboatwright** [comment]
_**I have read the CLA Document and I hereby sign the CLA**_

**Comment by bboatwright** [comment]
recheck

**Comment by bboatwright** [comment]
recheck

**Comment by matslina** [comment]
Sorry for the delayed reply here. Just wanted to mention, in case it wasn't already clear, that this is failing CI due to the API endpoint being to slow to respond.

**Pull request closed without merging**
