### PR TITLE
added synth solar monitoring app

### PR DESCRIPTION
**Pull request by maxalines**
The Synth Solar Monitoring app allows anyone who has solar inverters from particularly manufacturers (currently SolaX, Givenergy and Rahvolt - but many more to come!) to monitor their real time performance of their solar system in the Tidbyt app.

We are UK-based and primarily provide this for the customers we supply solar systems too, but we are happy to add anyone who has the inverters named above. The data is cleaned and normalised via our own server and API and so if you would like your inverter added please email as at hi@synth.solar and we can provide instructions on the information that we need from you to get it added.

synth_solar

### CODE REVIEW

**Comment by maxalines** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by maxalines** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by maxalines** [comment]
**_I have read the CLA Document and I hereby sign the CLA_**

**Comment by matslina** [comment]
@maxalines Most of the time when the CLA check isn't working, it's due to the email address associated with the commits not being registered under the Github account making the PR. Could that be the case here?

**Comment by maxalines** [comment]
Hi @matslina - yes I think so! I submitted this PR (@maxalines) but the commit was done by @abdullahwaqar - we have both been working on this but @abdullahwaqar is the man is the real developer here! Let me know if we need to do anything here.

**Comment by matslina** [comment]
Yeah I think the easiest path forward would be to either add that email address to the Github account (which seems a bit weird), or to update the email address on the commit itself (either via a new PR, or force pushing).

**Comment by abdullahwaqar** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by matslina** [comment]
Thanks!

**Pull request merged**
