### PR TITLE
Initial commit

### PR DESCRIPTION
**Pull request by dakotawalker**
# Description
Replace this with a description of your changes.

chartmogul_arr

# Copilot

### Summary
📊💰🔑

This pull request adds a new applet for displaying ChartMogul monthly ARR on the tidbyt device. It includes the applet code in `chartmogul_arr.star` and the manifest file in `manifest.yaml`.

> _`ChartMogul ARR`_
> _Applet for tidbyt device_
> _`main` and `manifest`_

### Walkthrough
* Create and register a new applet for displaying ChartMogul monthly ARR ([link](https://github.com/tidbyt/community/pull/1644/files?diff=unified&w=0#diff-6bf608c8d88344a710c418deb21270b9fb2c19ca64b4f8b6bf8ba11b75c83c5fR1-R62), [link](https://github.com/tidbyt/community/pull/1644/files?diff=unified&w=0#diff-4d5591ec1872348d1fe66a96459b5980533a4e7645e7078f37f5bdeda515c9f5R1-R8))
  - Define the main function `main` in `chartmogul_arr.star` that takes a config parameter and returns a render.Root object with the ARR value ([link](https://github.com/tidbyt/community/pull/1644/files?diff=unified&w=0#diff-6bf608c8d88344a710c418deb21270b9fb2c19ca64b4f8b6bf8ba11b75c83c5fR1-R62))
  - Define the schema function `get_schema` in `chartmogul_arr.star` that returns a schema.Schema object with the required config fields, such as the API key ([link](https://github.com/tidbyt/community/pull/1644/files?diff=unified&w=0#diff-6bf608c8d88344a710c418deb21270b9fb2c19ca64b4f8b6bf8ba11b75c83c5fR1-R62))
  - Use the `base64`, `http`, `render`, and `schema` modules to encode the API key, make a GET request to the ChartMogul API, parse the JSON response, and format the output ([link](https://github.com/tidbyt/community/pull/1644/files?diff=unified&w=0#diff-6bf608c8d88344a710c418deb21270b9fb2c19ca64b4f8b6bf8ba11b75c83c5fR1-R62))
  - Add the manifest file `manifest.yaml` with the applet metadata, such as the id, name, summary, description, author, fileName, and packageName ([link](https://github.com/tidbyt/community/pull/1644/files?diff=unified&w=0#diff-4d5591ec1872348d1fe66a96459b5980533a4e7645e7078f37f5bdeda515c9f5R1-R8))

### CODE REVIEW

**Comment by dakotawalker** [comment]
This app displays the ChartMogul monthly ARR for a given user's ChartMogul account via their api key. 

If there is no API key, then "No API Key" is rendered. 

If there is an API Key that is invalid, then "API Failure" is rendered.

If the request succeeds, then the value is displayed. For example: "$968k"

**Comment by dakotawalker** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by matslina** [comment]
Hey @dakotawalker. Thanks for the PR.
It would be great if the app could display a default graphic (with mocked data if need be) that shows what the app will look like once it's fully set up and installed on a Tidbyt. That allows us to provide preview graphics for users so they get an idea of whether or not this is the right app for them.

**Comment by matslina** [comment]
Hey. Thanks! What I'm really looking for is for the app itself to be modified so that it outputs a sample graphic when no configuration has been provided. I.e., instead of "NO API KEY", the app should output a graphic that shows what it'll look like once it's set up.

**Comment by dakotawalker** [comment]
> 

Ah, understood. I went ahead and changed the "No API Key" message to an example amount. Thanks so much for taking your time to review this.

**Comment by dakotawalker** [comment]
Screenshot 2023-08-16 at 11 30 40 AM

**Pull request merged**
