### PR TITLE
awair: add cloud API support via bearer token, improve layout, mock data view

### PR DESCRIPTION
**Pull request by flavorjones**
# Description

The big change in this PR is the addition of **support for the Awair Cloud API** via a Bearer token. (Unfortunately the Awair Cloud API quotas are quite low, so the network cache TTL is 5 minutes.) The schema uses `Generated` fields for the needed values, but the app should be backwards-compatible with the configs of anyone who's already installed and configured the Local API.

**Mock data is now rendered when the app is unconfigured**, so the app store webp is a bit more informational for users.

The **display has been improved** a bit: table numbers line up, with more consistent whitespace; and the score circle and font are larger. The color maps have been updated to match the values in the [official Awair docs](https://docs.developer.getawair.com/).

See the README for more information.

## Screenshots

For a sense of the visual layout changes:

|  | screenshot |
|---|---|
| before this PR |  |
| with this PR |  |
| unconfigured |  |
| api error |  |

/cc @tabrindle who wrote the original version of this app at https://github.com/tidbyt/community/pull/1762

# Copilot

copilot:all

### CODE REVIEW

**Comment by flavorjones** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by flavorjones** [comment]
recheck

**Comment by matslina** [comment]
@tabrindle Any thoughts on this?

**Comment by flavorjones** [comment]
@matslina Thank you for tagging tabrindle (I also tagged him in the original description).

I'm wondering, if he doesn't respond, is there a way forward for this (and my other) PR? I'm just not aware of what the process is here, since this is my first contribution to a tidbyt app.

**Comment by tabrindle** [comment]
Hey, sorry I’ve been on leave, can take a look soon. I was recently putting
together some changes that would match the colors with the new IAQ/awair
score changes, and add the ability to map more than one device, but haven’t
finished it yet. I can rebase it on this work. As long as this is not a
breaking change, I’m ok with it.

Thanks for tagging me!

**Comment by matslina** [comment]
Looks to me like it'll be backwards compatible, but that's just at a glance. Unless you guys tell me differently, I'll merge later today or tomorrow.

**Comment by flavorjones** [comment]
Yes, as best I could I took care to make it backwards compatible (as far as my understanding goes of how the config is handled in the web client). Existing configs are intended to continue to work.

**Comment by matslina** [comment]
Off we go!

**Pull request merged**
