### PR TITLE
added archer dog

### PR DESCRIPTION
**Pull request by knockturn1**
# Description
Gif animation of our dog that past last year, named Archer! This is my first time be gentle ha, hoping to get this on TidByt for an xmas present.  

# Copilot

copilot:all

### CODE REVIEW

**Comment by knockturn1** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by knockturn1** [comment]
recheck

**Comment by knockturn1** [comment]
my email address was wrong in vscode. I corrected my email and recommitted. sorry about that!

**Comment by matslina** [comment]
Happy Holidays!

**Pull request merged**
