### PR TITLE
updated supported coins list to 20240201

### PR DESCRIPTION
**Pull request by hodgerpodger**
# Description
Only change was to update SUPPORTED_COINS to latest, as of 20240201.  This simply allows coingecko price app to have most up-to-date list of coins (instead of older 2022 version).

# Copilot

copilot:all

### CODE REVIEW

**Comment by hodgerpodger** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by matslina** [comment]
@aschober Thoughts on this one?

**Comment by hodgerpodger** [comment]
Would love to get this in, as I use this app everyday.  Alternatively, I may submit a different app name (after some time if no response) also to guarantee the original one stable, if that’s preferable.

**Comment by aschober** [comment]
@hodgerpodger @matslina GitHub makes viewing lots of line changes complicated. But LGTM.

**Pull request merged**
