### PR TITLE
Adding Near Earth Objects App

### PR DESCRIPTION
**Pull request by noahcolvin**
This app hits the Near Earth Object API [NeoWs](https://www.neowsapp.com/) to display the name of the next nearest object to Earth as well as the relative time, distance, and speed of when it will miss.

Also allows the user to configure kilometers vs miles.

neo_byt

### CODE REVIEW

**Comment by noahcolvin** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by noahcolvin** [comment]
recheck

**Comment by rohansingh** [comment]
@noahcolvin Looks great, thanks for the PR!

**Comment by rohansingh** [comment]
Hi @noahcolvin. Unfortunately I had to revert this because it was failing tests.

The flavor of Starlark we use on our server does not allow `while` loops. Is it possible to rewrite `find_soonest_starting` to use a `for` loop that ranges over a fixed sequence?

**Pull request merged**
