### PR TITLE
Add new app: exotic clocks

### PR DESCRIPTION
**Pull request by vzsky**

### CODE REVIEW

**Comment by vzsky** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by vzsky** [comment]
@matslina Just wandering if I should remove the python file for a review or is it in progress?

**Comment by matslina** [comment]
yeah that'd be good. in general, the review bot doesn't like subdirectories, and since (I believe) the graphics are all in the starlark file they don't really need to be in here either.

**Comment by matslina** [comment]
sorry for the delay, I somehow kept missing this one

**Comment by vzsky** [comment]
No problem!

**Pull request merged**
