### PR TITLE
New App: Snake Clock

### PR DESCRIPTION
**Pull request by paxos**
snake_clock

Adds a new app:
- shows a clock in the foreground
- background shows a snake moving around in a random pattern
- using global state to sync the movement for all users
- this means every user will see the same snake movements 🎉

### CODE REVIEW

**Comment by paxos** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by drudge** [comment]
This looks great! Would you mind adding support for 12-hour format?

Here is an example from another community app: 
https://github.com/tidbyt/community/blob/main/apps/underwaterclock/underwater_clock.star#L165-L170
https://github.com/tidbyt/community/blob/main/apps/underwaterclock/underwater_clock.star#L78-L83

**Comment by paxos** [comment]
> This looks great! Would you mind adding support for 12-hour format?
> 
> Here is an example from another community app: https://github.com/tidbyt/community/blob/main/apps/underwaterclock/underwater_clock.star#L165-L170 https://github.com/tidbyt/community/blob/main/apps/underwaterclock/underwater_clock.star#L78-L83

For sure :) -  thanks for checking!

**Comment by paxos** [comment]
12 / 24 hour setting added
Also made sure to show time for the correct timezone 🤦‍♂️

**Pull request merged**
