### PR TITLE
New app: METAR (aviation weather)

### PR DESCRIPTION
**Pull request by avalys**
This is a new app that is capable of displaying airport METARs and derived flight category summaries: VFR (visual flight rules), IFR (instrument flight rules), MVFR (marginal VFR), etc.

It supports displaying the raw METAR text for a single airport, or scalable summary displays showing flight category for 2-15 airports.

The user enters a list of airport ICAO codes as a comma-separated text config.
 
metar-15
metar-4
metar-8
metar-1

### CODE REVIEW

**Comment by avalys** [comment]
I have read the CLA Document and I hereby sign the CLA.

recheck

**Comment by avalys** [comment]
recheck

**Comment by avalys** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by avalys** [comment]
IMG_5002
IMG_5004
IMG_5001

**Comment by matslina** [comment]
Neat!

**Comment by wrycu** [comment]
Now that this is merged, any idea how long it will take to show up in the store?

**Pull request merged**
