### PR TITLE
New App: Xtrabyt

### PR DESCRIPTION
**Pull request by vmitchell85**
This app provides integration with Xtrabyt.

Xtrabyt is a platform built to provide a way for users to create custom drawings for their Tidbyt. Plans exist to further expand the offerings of Xtrabyt to include integrations with other online services to display other information and data.

Thanks for considering my contribution.

Here is the default screen:
xtrabyt

### CODE REVIEW

**Comment by vmitchell85** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by vmitchell85** [comment]
recheck

**Comment by rohansingh** [comment]
So cool! ❤️

**Comment by matslina** [comment]
This is awesome! =)

**Pull request merged**
