### PR TITLE
New App: Mondrian clock

### PR DESCRIPTION
**Pull request by theredwillow**
This app is a decorative clock face in the style of Piet Mondrian's De Stijl compositions.

A digital readout is available as a boolean configuration option in the schema. (I didn't know how to update the schema setting for the `pixlet render`.)

An explanation of how to read the clock is included in the README.md.

mondrianclock
The above clockface represents **5:38**.

### CODE REVIEW

**Comment by theredwillow** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by theredwillow** [comment]
It's giving a warning that `app summaries should start with an uppercased character`, but mine does ("M" for Mondrian). That appears to be a bug.

**Comment by theredwillow** [comment]
I didn't see the `pixlet create` function until after I had manually created my app by following the precedent code. It doesn't mention on [the page](https://tidbyt.dev/docs/publish/publishing-apps#3-create-your-app) that you need to cd into your own app's folder.

I tried running that and taking the result from it to pass the buggy character checker. Seems to have worked.

**Comment by danielsitnik** [comment]
Holy crap now that is a crazy clock!
I will need to read the manual to understand that 🤣

**Comment by jvivona** [comment]
holy crap - I think my brain just broke, looking at that.   A literal work of art.

you can render the sample image in GIF format via the pixlet render ( --gif)  command line.  Gifs are included in the community & can be committed.

**Comment by theredwillow** [comment]
@jvivona I would love to render a gif of it looping through the whole thing, but...

1. [Gifs are limited to 15 seconds](https://tidbyt.dev/docs/reference/gifs#gif-is-15-seconds-in-length-or-loops-cleanly-if-less-then-15-seconds). Even if I could, it would either loop through so fast that it would barely make sense, or it would be like 12 minutes long. If I only included the 12 in this tutorial, then writing up the information would be difficult.
2. This was engineered to be a clockface. [Animating ](https://tidbyt.dev/docs/reference/animation) it to cycle would involve coding a very messy scaffold codework with.

**Comment by theredwillow** [comment]
@jvivona `unknown flag: --jpg` Is this documented anywhere? How do I do that?

Also, it would be nice to include the twelve sample images as a gif for the app store (even if there's no room for explanation 😓). Is there a Starlark way to `setTimeout`?  If so, I could wrap my `render.Root` into a function and loop over that... Much, much simpler than working with Animation.

**Comment by jvivona** [comment]
pixlet render can't emit jpgs.  take your webp files & convert them.     this is what we use here.  https://ezgif.com/webp-to-jpg

**Comment by jvivona** [comment]
I can't answer about how the app store works.

**Pull request merged**
