### PR TITLE
Add IsItUp

### PR DESCRIPTION
**Pull request by Jonesie**
My first attempt to contribute.  Please be kind :)  

This app displays the status of a web site from a specified URL - either 'OK' or 'Failed : <response code>' is displayed.  It will also optionally try to extract a version number from a JSON response that looks like :
```
{ 
  "version": "1.2.3.4",
  ...
 }

```

### CODE REVIEW

**Comment by Jonesie** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by Jonesie** [comment]
recheck

**Comment by matslina** [comment]
Hey @Jonesie and thanks for the PR! Looks like a great contribution.

Unfortunately we're currently not able to merge apps that call user-provided URLs. This is so to protect against potential malicious behavior where someone tries to abuse our platform to flood/spam/misbehave by calling external hosts. I hope we'll be able to find a workaround for this problem, but right now we won't be able to merge this app. =(

Adding a label to this PR so that we can revisit it if/when we have a solution in place.

**Comment by Jonesie** [comment]
> Hey @Jonesie and thanks for the PR! Looks like a great contribution.
> 
> Unfortunately we're currently not able to merge apps that call user-provided URLs. This is so to protect against potential malicious behavior where someone tries to abuse our platform to flood/spam/misbehave by calling external hosts. I hope we'll be able to find a workaround for this problem, but right now we won't be able to merge this app. =(
> 
> Adding a label to this PR so that we can revisit it if/when we have a solution in place.

Hi, that makes perfect sense. Ive removed them.

**Comment by Jonesie** [comment]
No possible to do this

**Pull request closed without merging**
