### PR TITLE
UPDATE: Vgk next game

### PR DESCRIPTION
**Pull request by theimpossibleleap**
# Description
Changed to call response.json() once per recommendation. Thank you!

# Copilot

copilot:all

### CODE REVIEW

**Comment by theimpossibleleap** [comment]
Added another commit that updates the base64 pixel art to be a lot cleaner! Thank you.

**Comment by theimpossibleleap** [comment]
Added another commit to change the time format. Hopefully these make it in! Also, when pull request is complete, will the App update on my Tidbyt automatically, or do I need to remove it and re-add it? Any help is appreciated! Thank you.

**Comment by matslina** [comment]
Hey. Sorry for the delay. We've been heads down on Gen 2 stuff for the past weeks, which unfortunately results in us neglecting the community repo... =(

This PR has a conflict which is preventing me from merging it. Please rebase your branch onto the latest version of the main branch. This means updating your branch with the latest changes from the main branch and resolving any conflicts that arise, which in turn will allow us to merge it.

If that sounds like gibberish -  and a lot of git magic does sound like gibberish, so don't sweat it - you can also create a completely new fork of the community repo, apply your edits there (e.g. by just copying over the latest versions of the relevant files from this fork), and then opening up a brand new PR.

Once the PR is merged, the app will update automatically without any need for you to do anything on your side. The updated app should appear on your Tidbyt(s) in a matter of minutes.

**Comment by theimpossibleleap** [comment]
Hey @matslina! No problem at all, hope y'all are settling in now. I tried to do the rebase but I'm not sure if I did it right. Please let me know. If I didn't, I'll just do the fork method. Thank you!

**Comment by matslina** [comment]
Afraid the conflict is still there. A brand new fork should hopefully do the trick.

**Pull request closed without merging**
