### PR TITLE
Launching the Tidbyt Outlook Calendar App

### PR DESCRIPTION
**Pull request by Matt-Pesce**

### CODE REVIEW

**Comment by Matt-Pesce** [comment]
outlook_calendar

Adding animated GIF here - hope this is the right place.

**Comment by matslina** [comment]
Hey @Matt-Pesce, and thanks for the PR! I know a lot of people will enjoy this contribution. =)

We'd like to set up some official Tidbyt credentials and migrate this over to use those before publishing it to everyone. First step would be to merge as is, do some testing, and then swap out the credentials. I hope that sounds good to you?

**Comment by matslina** [comment]
Gonna merge but hold off on publishing until we've figured out the credentials.

**Comment by Matt-Pesce** [comment]
@matslina  sorry for the delay - yes this sounds like a good plan and happy to be of assistance with Credentials, as needed.

**Pull request merged**
