### PR TITLE
New App - Spot the International Space Station

### PR DESCRIPTION
**Pull request by rjison**
This application asks for your SpotTheStation.nasa.gov RSS feed for your location and will display the next viewing opportunity as the ISS flies overhead.

### CODE REVIEW

**Comment by rjison** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by rjison** [comment]
recheck

**Comment by rjison** [comment]
This one tells you when you can next see it over your house. The other one tells you where it is at the moment. 

I think it should be it’s own app because there is too much info to display at once, and they provide very different pieces of info. 

The audience for my app wants to plan their walk outside and know where to look. They don’t care where it is otherwise. 

Thanks
Rob

**Comment by rohansingh** [comment]
Sounds good. Please run the `make format` command to fix the formatting of the Starlark file. After that the tests should pass and we'll be able to merge it.

**Comment by rjison** [comment]
Please excuse my ignorance, but can you direct me to instructions to "make
format comand to fix the formatting of the Starlark file"? I followed all
the steps in the guide to make an app and didn't see this step.  I used
'make' to create the app, but I can't figure out what I need to do to fix
this formatting issue you refer to. I'd appreciate your help here, this is
new to me. Thanks!

**Comment by rohansingh** [comment]
No worries. In the same way that you ran `make app` to create the app, you should be able to run `make format`. This should fix the formatting.

If that doesn't work let me know and I can also run it and push the fix from my end.

**Comment by rohansingh** [comment]
Oops sorry, this actually got merged with the formatting issues embedded. I fixed them afterward. No action required on your part, this should be live soon.

**Comment by rjison** [comment]
Thanks for helping me with this, I really appreciate it.

when I run 'make format' I get the following error:

make: *** No rule to make target 'format'. Stop.

**Comment by rjison** [comment]
That's great! I have a couple other app ideas, if you have any ideas to get
my 'make format' working, I'd appreciate it. I'd hate to bother you again
with this.

Thanks
Rob

**Comment by rohansingh** [comment]
@rjison No worries, it's not a bother. The `make format` command should work, but only if run from the root of the community repo, eg., the `community` directory.

If it's still not working please join us in Discord and we can try to troubleshoot there.

**Pull request merged**
