### PR TITLE
New app to show islamic prayer times

### PR DESCRIPTION
**Pull request by EslamMoh**
# Description
This app displays the prayer times for today's date based on the user location and the method of prayer time calculation. The location, timezone and prayer time calculation method are configurable in Tidbyt app based on the user input.

# Copilot

### Summary
📄📝🕌

This pull request adds a new app for displaying Islamic prayer times on Tidbyt devices. It includes the necessary metadata file `manifest.yaml` and a documentation file `README.md` for the app.

> _`manifest.yaml`_
> _Metadata for Tidbyt app_
> _README explains_

### Walkthrough
* Create and document a new app for displaying prayer times on Tidbyt ([link](https://github.com/tidbyt/community/pull/1723/files?diff=unified&w=0#diff-9887e196575faacc367a2aa02abc345e33b4617db03f04869b4f0bbf7dc13c90R1-R8), [link](https://github.com/tidbyt/community/pull/1723/files?diff=unified&w=0#diff-c88ac26d8682c67f4072918ca0b450a3e51f7c5f554cfc8f3b6340cfd14f710fL1-R25))

### CODE REVIEW

**Comment by EslamMoh** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by EslamMoh** [comment]
recheck

**Comment by matslina** [comment]
Thanks for the PR!

**Comment by EslamMoh** [comment]
Thank you @matslina for approving the PR 🙏🏻

**Comment by EslamMoh** [comment]
@Ali-Mahmood Thank you so much for the feedback 🙏🏻🤩 It's live now 🎊

**Pull request merged**
