### PR TITLE
PurpleAir equations update

### PR DESCRIPTION
**Pull request by frame-shift**
# Description
The PurpleAir Tidbyt app previously used an older method to calculate AQI based on an outdated US EPA equation. PurpleAir now uses more updated US EPA conversion methods, specifically a five-step algorithm depending on current PM2.5 levels. This fork has updated the PurpleAir Tidbyt app to reflect US EPA's new conversion method that PurpleAir uses.

Full documentation from the EPA: https://cfpub.epa.gov/si/si_public_record_report.cfm?dirEntryId=353088&Lab=CEMM
Final equations are found on Slide 26, which are the same ones used by PurpleAir.

# Copilot

### Summary
🆕🔥📝

Updated the `purpleair` app to use a new EPA algorithm for PM 2.5 correction based on wildfire data. This improves the accuracy and consistency of the air quality readings.

> _`PM 2.5` value_
> _Updated with new formula_
> _Wildfire smoke in fall_

### Walkthrough
*  Update PM 2.5 calculation algorithm to use new EPA formula ([link](https://github.com/tidbyt/community/pull/1727/files?diff=unified&w=0#diff-d0bf8e870e7e3f045a0eb2378287e162705fc649e8653052e62b0136b219647cL395-R418))

### CODE REVIEW

**Comment by frame-shift** [comment]
I have read the CLA Document and I hereby sign the CLA

**Review by frame-shift — COMMENTED** [review]
Fixing for starlark notation (sorry, I'm not a programmer! 🙃)

**Comment by jvivona** [comment]
@frame-shift do you need help getting this to pass the checks?    I'm a heavy PurpleAir user & I'd like to see this make it into the app.   we also have to get @posburn to concur with the changes..

**Comment by frame-shift** [comment]
> @frame-shift do you need help getting this to pass the checks? I'm a heavy PurpleAir user & I'd like to see this make it into the app. we also have to get @posburn to concur with the changes..

Yes please! I'd really appreciate the help. I tried Googling how to do everything and did the best I could. Things that we need:

1. Double-checking to make sure the coded equations accurately match EPA's slide (I'm pretty confident it does)
2. Getting it past the checks
3. Getting @posburn 's input

(Plus I'm sure other things that I haven't thought of yet)

**Comment by jvivona** [comment]
@frame-shift  - it was a fairly simple error you were battling with you code.    I fixed that.  
While I was in there though I went ahead and moved the HTTP GETs over to the new caching method.

we need to get @posburn to review & approve.  

I have not validated your calculations - I'm assuming you have done all that testing work.

**Review by posburn — COMMENTED** [review]
@frame-shift I double-checked the code with the updated calculations on the slide and they appear to match. Nice work! Thanks for working on this. I'm busy on other things at the moment and am not setup to test these changes but the code looks good to me.

@jvivona Thanks for updating the caching. I'm also not up to date on the caching changes but am assuming you have verified that the caching is working locally? The code looks good to me as well.

So, all changes look good to me.

**Comment by frame-shift** [comment]
> @frame-shift I double-checked the code with the updated calculations on the slide and they appear to match. Nice work! Thanks for working on this. I'm busy on other things at the moment and am not setup to test these changes but the code looks good to me.

Appreciate it! Thanks for your input. And yeah, I've been checking them against data and they appear to work correctly.

**Pull request merged**
