### PR TITLE
update halloween_countdn app to change display on Halloween

### PR DESCRIPTION
**Pull request by arock95**
Updated Halloween Countdn app to say "Halloween" on Halloween instead of "0 days".

### CODE REVIEW

**Comment by jvivona** [comment]
@arock95 becuase you have safe modules (all 3 green checks) - have you seen if you can auto merge with the old "  :shipit: " comment.  I know it the past it's worked - if you have all 3 green.

I want this update (  #purelyselfish )

**Comment by arock95** [comment]
I wasn't familiar with that @jvivona so thanks for sharing!  Assuming it works via PR comment, :shipit:

**Comment by jvivona** [comment]
I know it used to work - they may have taken it out.  I think it has to be it's own comment, not inline & it has to be from the author (you).

**Comment by adilansari** [comment]
:shipit:

**Comment by jvivona** [comment]
whomp whomp.   sorry - guess it's been removed by the team.   I'm sure they will get to it here shortly.

**Comment by arock95** [comment]
No worries, neat to know that it was possible at one time!

**Pull request merged**
