### PR TITLE
Adds new general bike share feed specification applet

### PR DESCRIPTION
**Pull request by snorremd**
The PR implements a new bikeshare applet that supports bikeshare companies using the [general bikeshare feed specification](https://github.com/NABSA/gbfs). The applet shows the availability of bikes and parking respectively for a user selected provider and stations.

The applet allows users to select one of the providers listed in [NABSA's systems list](https://github.com/NABSA/gbfs/blob/master/systems.csv). It uses `schema.Generated` to facilitate selection of the two stations to show statuses for. Caching is used for all requests to minimise load on GBFS APIs and a user agent links back to the app.

Any feedback is welcome!

I should probably improve the error handling as it now uses the `fail()` function which is not best practice.

bikeshare

### CODE REVIEW

**Comment by snorremd** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by snorremd** [comment]
I had to rewrite the commit history as I had used my work email instead of my personal email in the commits. Seem to have rewritten one too many commit. Will fix the history if necessary and add some better error handling soon.

**Comment by andjosh** [comment]
I was starting to build this! Glad to have a PR started and excited to use this!

**Comment by matslina** [comment]
This is really sweet!

**Comment by snorremd** [comment]
> This is really sweet!

Thank you! I really appreciate you taking the time to review and merge. 😄 Loving my Tidbyt so far.

**Pull request merged**
