### PR TITLE
New App: SolarEdge Production

### PR DESCRIPTION
**Pull request by BillyMcSkintos**
SolarEdge PV Production Monitoring
solaredge_prod

### CODE REVIEW

**Comment by BillyMcSkintos** [comment]
Still failing. No idea where this variable might be...

`pixlet lint --fix apps/solaredgeprod/solaredge_prod.star
apps/solaredgeprod/solaredge_prod.star:37: unused-variable: Variable "config" is unused. Please remove it. (https://github.com/bazelbuild/buildtools/blob/master/WARNINGS.md#unused-variable)
Error: linting failed with exit code: 4`

**Comment by BillyMcSkintos** [comment]
@matslina cleared the errors. Ready when you are.

**Comment by markazali** [comment]
Great app! I love the visualization. It's nice not having to open my app/solaredge website anymore.

**Comment by BillyMcSkintos** [comment]
Thank you, its my first app ever so glad its working and that someone beside me likes it. I have yours running too. Its nice to have the additional values to monitor too.

**Pull request merged**
