### PR TITLE
Njtransitdepartureapp

### PR DESCRIPTION
**Pull request by Jason-J-Hunt**
# Description
Update URL and HTML search of station names to resolve issue where stations werent being loaded for users to select.
# Copilot

### Summary
🚉🌐🔧

Update `njtransit` app to use a more reliable data source. Change the URL, request, and selector to match the new format.

> _`NJ_TRANSIT_URL`_
> _New source for station data_
> _Autumn leaves change too_

### Walkthrough
* Change the URL and CSS selector for scraping station names and codes from the NJ Transit stations page (`apps/njtransit/nj_transit.star` [link](https://github.com/tidbyt/community/pull/1955/files?diff=unified&w=0#diff-3a3c3995bbb36f3ae706f871a912461edf0adf1b954a19a1f89cdca536d51e24R51), [link](https://github.com/tidbyt/community/pull/1955/files?diff=unified&w=0#diff-3a3c3995bbb36f3ae706f871a912461edf0adf1b954a19a1f89cdca536d51e24L541-R542), [link](https://github.com/tidbyt/community/pull/1955/files?diff=unified&w=0#diff-3a3c3995bbb36f3ae706f871a912461edf0adf1b954a19a1f89cdca536d51e24L553-R554))

### CODE REVIEW

**Comment by matslina** [comment]
Hey. Thanks for the PR.

As you might've noticed already, the build is failing due a performance check. I think the main culprit is the ~0.5MB page your downloading to extract departures. I don't have any immediate ideas for how to fix that, but if it's possible to download the same data in a more stripped down format, then that might get you a green build.

**Comment by Jason-J-Hunt** [comment]
Fixed the profiling error

**Comment by dougbyrne** [comment]
Hi, how do we move this forward?

**Comment by matslina** [comment]
Let's give it a try. I'm guessing caching is gonna smooth over the slow data retrieval most of the time.

**Comment by Jason-J-Hunt** [comment]
> Let's give it a try. I'm guessing caching is gonna smooth over the slow data retrieval most of the time.

I mean this app has been here for like a year with no issues. I will be creating another PR within the next week to fetch from a private API that got setup to host the Transit data.

**Pull request merged**
