### PR TITLE
borisbikes: updated secret

### PR DESCRIPTION
**Pull request by matslina**

### CODE REVIEW

**Comment by matslina** [comment]
@dinosaursrarr Forgot to check the secret, and it too had to be updated to match the .star filename.

**Comment by dinosaursrarr** [comment]
Thanks! I might need to check a couple of my other apps. 

I was never quite clear if the app name for encrypting was the folder name or the script name. Make app generated them differently when there's a space in the name. 

Might be a good one to add to the new docs site? :)

**Comment by matslina** [comment]
You know what, I'm an idiot. This secret was perfectly fine as it was. My bad! I'll restore it in a bit.

**Comment by matslina** [comment]
but yeah it'd be good to have written down on the doc site! =D

**Pull request merged**
