### PR TITLE
Added the option to display moon phase text in Chinese.

### PR DESCRIPTION
**Pull request by vtsao**
# Description

Changed the display text option toggle to a dropdown to support this.

cc @alan-fleming (original author)
Thanks to @misshenyc for the Chinese characters pixel art.

# Preview

This is what the various moon phases look like with Chinese text:

0_new_moon
1_waxing_crescent
2_first_quarter
3_waxing_gibbous
4_full_moon
5_waning_gibbous
6_last_quarter
7_waning_crescent

# Copilot

### Summary
🌙🇨🇳🗣️

This pull request adds a new feature to the `phaseofmoon` app that allows users to choose the language of the moon phase text or hide it altogether. It uses a new set of images and a new variable for the Chinese text, and changes the app configuration schema to use a dropdown field instead of a toggle.

> _The moon is rising in the dark_
> _A silent witness to our fate_
> _We choose the language of our mark_
> _`display_text` seals our state_

### Walkthrough
*  Add support for displaying moon phase in Chinese as an option for the user ([link](https://github.com/tidbyt/community/pull/1816/files?diff=unified&w=0#diff-d026a32008801b669de52e78dc6cb0ba9d1aa6e1d62ab9ae10ff2c6abea42dfaR76-R87), [link](https://github.com/tidbyt/community/pull/1816/files?diff=unified&w=0#diff-d026a32008801b669de52e78dc6cb0ba9d1aa6e1d62ab9ae10ff2c6abea42dfaR106), [link](https://github.com/tidbyt/community/pull/1816/files?diff=unified&w=0#diff-d026a32008801b669de52e78dc6cb0ba9d1aa6e1d62ab9ae10ff2c6abea42dfaR112), [link](https://github.com/tidbyt/community/pull/1816/files?diff=unified&w=0#diff-d026a32008801b669de52e78dc6cb0ba9d1aa6e1d62ab9ae10ff2c6abea42dfaL104-R127), [link](https://github.com/tidbyt/community/pull/1816/files?diff=unified&w=0#diff-d026a32008801b669de52e78dc6cb0ba9d1aa6e1d62ab9ae10ff2c6abea42dfaR159-R173), [link](https://github.com/tidbyt/community/pull/1816/files?diff=unified&w=0#diff-d026a32008801b669de52e78dc6cb0ba9d1aa6e1d62ab9ae10ff2c6abea42dfaL148-R189))

### CODE REVIEW

**Comment by vtsao** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by vtsao** [comment]
recheck

**Comment by vtsao** [comment]
Friendly ping, can I get somebody to take a look? Thanks.

**Comment by vtsao** [comment]
Pinging again, can someone PTAL?

**Comment by alan-fleming** [comment]
I'm loath to approve when I have no knowledge of the language.  Can this be independently confirmed?

**Comment by vtsao** [comment]
Thanks for responding @alan-fleming.

@betterengineering or @matslina do you know anybody in the Tidbyt community that can read Chinese to help approve?

Otherwise here are the characters. You can paste them into Google Translate to verify ([example](https://translate.google.com/?sl=auto&tl=en&text=%E6%96%B0%E6%9C%88&op=translate)):

- New moon: 新月
- Waxing crescent: 眉月
- First quarter: 上弦月
- Waxing gibbous: 上凸月
- Full moon: 满月
- Waning gibbous: 下凸月
- Last quarter: 下弦月
- Waning crescent: 残月

This page also has translations: https://languagedrops.com/word/en/english/chinese/translate/phases_of_the_moon/
Some are slightly different than some of the characters used here (there are multiple ways to describe moon phases in Chinese).

**Comment by alan-fleming** [comment]
OK, that looks good. Thank you!

**Comment by vtsao** [comment]
Friendly ping for @betterengineering or @matslina can you PTAL? Thanks!

**Comment by matslina** [comment]
Thanks for the PR @vtsao, and thanks for pitching in on the review @alan-fleming!

Sorry for the delay. Busy couple of weeks with [Gen 2](https://gen2.tidbyt.com/) in flight and so on.

**Pull request merged**
