### PR TITLE
New app: Mempool

### PR DESCRIPTION
**Pull request by PMK**
# Description
This new app will display the current mempool Bitcoin fee statistics in the orange block on the left side. And display the latest mined block with details in the purple block on the right side. The data is provided by [mempool](https://github.com/mempool) via their public REST APIs.

# Copilot

### Summary
📄🌟📚

This pull request adds a new applet for the Tidbyt device called `mempool`, which shows Bitcoin mempool and block data. It includes the required `manifest.yaml` file, the Starlark code in `mempool.star`, and a `README.md` file with a description and screenshot of the applet.

> _`mempool` applet_
> _adds manifest, code, docs_
> _autumn of Bitcoin_

### Walkthrough
* Create and configure a new applet for displaying Bitcoin mempool statistics ([link](https://github.com/tidbyt/community/pull/1833/files?diff=unified&w=0#diff-33d5581ed942325ce2bf7b3f7fd6e7ecfa54d64f9bb5fbcf9c24f28db41b5fefR1-R8), [link](https://github.com/tidbyt/community/pull/1833/files?diff=unified&w=0#diff-9701fc429af82e57c4c4982221a567a147aa9da5cc3a4181d08179faf2ccaf23R1-R158))
* Document the applet functionality, data source, and appearance ([link](https://github.com/tidbyt/community/pull/1833/files?diff=unified&w=0#diff-732f48d7788765737fabc8d3d36073113ec6370f5f7dd02fe5ad7d5fbe6f238dR1-R6))

### CODE REVIEW

**Comment by PMK** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by PMK** [comment]
recheck

**Comment by PMK** [comment]
recheck

**Comment by noahpodgurski** [comment]
The yellow on yellow text is a bit hard to read

**Pull request merged**
