### PR TITLE
New App: Tilt Hydrometer

### PR DESCRIPTION
**Pull request by DSUmjham**
This pull request is to add a new Tidbyt app, tilthydrometer. The Tilt Hydrometer logs and tracks data throughout fermentation via Bluetooth. Log data is published to a Google Sheet generated by Tilt and shared with a user-specified Google account. This app retrieves the following data from the Sheet and displays it on the Tidbyt:

### CODE REVIEW

**Comment by DSUmjham** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by DSUmjham** [comment]
@matslina Thanks for taking a look! The Tilts are pretty cool, I just started using one and thought it'd be great to tie into my Tidbyt. Two solutions come to mind for showing the app without the configuration; do you have any preference between the two or other ideas?

1. Copy a Tilt spreadsheet to a hosted location outside of Google that does not require the API key. 
2. Embed sample JSON data in the app to populate the necessary display values if no API/Sheet link are provided.

**Comment by matslina** [comment]
I think sample data might be easiest! No need to worry about the spreadsheet disappearing later on that way.

Btw, might be good to add a bit more info to the app description about how to get the key for the sheet as well. Just to make things smoother for users.

**Comment by DSUmjham** [comment]
Sounds great! I've added sample data to the app, which will now work without user configuration. I also updated the manifest file to include a link to Google's instructions on creating an API key. Let me know if you would like to see any other changes.

**Pull request merged**
