### PR TITLE
Modified App Soccermens - added option to select team display order

### PR DESCRIPTION
**Pull request by jesushairdo**
The app Soccermens displays teams in US order, visiting team followed by home team.

This request adds ability to select whether visiting team or home team is shown first

### CODE REVIEW

**Comment by jesushairdo** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by jvivona** [comment]
@jesushairdo WOW - that's awesome. I'd want to do this for both mens & womens. I just made a bunch of changes to both apps in PR#1072 - I don't see any conflicts in the code - but I don't think we can merge/merge in sequence without rebasing after 1072 gets merged - because one set of the changes will get over-ridden or the change deltas will be in the wrong places depending on which PR goes in first. Let me see about merging this into my branch and pushing it back out - there's easier ways to do it without a lot of duplicate code.  I get what you are doing.

**Comment by jesushairdo** [comment]
Sounds good, look forward to seeing it :)

**Comment by jvivona** [comment]
@matslina was working hard today  1072 just got merged.  I'll rebase on my end & get this inserted.   I'm not going to mod the upper code of home & away - otherwise debugging who is home & away has challenges - but I'll get the sequence right - just before we start the render in lines 210.

**Comment by jesushairdo** [comment]
reworked by original developer under separate pull request

**Pull request closed without merging**
