### PR TITLE
Added: optional clock

### PR DESCRIPTION
**Pull request by kaffolder7**
Added additional feature to display the active time (clock) as this is helpful in my case. I have been using this app as the only app on my Tidbyt at nighttime instead of the default built-in, nighttime display of the time. Great initial app by @alan-fleming!! 🎉 Happy to share and opening a PR as I think this feature may also be helpful to others as well.

### CODE REVIEW

**Comment by kaffolder7** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by kaffolder7** [comment]
@alan-fleming – Would you be willing to review this PR? Git bot states that a manual review is required since obviously I am not the original author.

I added a clock to your Phase of Moon app as I found that was one thing I was desiring. Opening my changes as a PR so others can hopefully benefit from the addition. (FYI: I added some schema configuration to the app so that this can be enabled/disabled. Defaults are configured to phase of moon text w/ optional clock.)

**Comment by alan-fleming** [comment]
Hi there. Apologies for the delay, I've been travelling with work and my time has not been my own. I'm OK with these changes.

**Comment by kaffolder7** [comment]
> Hi there. Apologies for the delay, I've been travelling with work and my time has not been my own. I'm OK with these changes.

Thanks so much!! 😀

@matslina, can we get this PR merged in? @alan-fleming has approved added feature.

**Comment by kaffolder7** [comment]
I so appreciate you @rohansingh! 🫶  I know Mats probably has a LOT going on right now. Was wanting to get this merged since my fork was held up by some other PR's I'd like to submit. (I was dumb and didn't branch my fork with these changes. I'll create branches on my fork and submit those as PR in the future.)

**Comment by rohansingh** [comment]
@kaffolder7 Thanks for the PR! Yeah we are both swamped right now, working on firmware/software for Gen 2.

**Pull request merged**
