### PR TITLE
made purdue basketball team stat app

### PR DESCRIPTION
**Pull request by Griffinov22**
# Description
I made an app that shows the team standings of the Purdue men's basketball team.

This is my first time using Starlark and commiting code to this repository, so I am completely open to constructive critisism.

I am using an api, and I require users of my app to include their own api_key upon using my app.

purdue_basketball

# Copilot

copilot:all

### CODE REVIEW

**Comment by Griffinov22** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by matslina** [comment]
Hey @Griffinov22, and thanks for the PR!

The files you've added in this PR are not placed entirely correctly in the file structure of the repo. Apps need to go under `apps/<name>/`. You can look at the other directories in there to get a sense of how it all works.

Since you asked for feedback, I thought I'd also mention that the embedded graphic could be scaled down ahead of time to keep the size of the script down a bit. Ideally, you scale it down to the exact dimension you're using in the app, so it doesn't have to be rescaled at runtime, if that makes sense. To cut the size even further, you could look into stripping any EXIF data from the file, e.g. using `exiftool -all= thatfile.png`.

**Review by matslina — CHANGES_REQUESTED** [review]
Manifest and starlark needs to go into a separate directory, e.g. `apps/purduebasketball/`.

**Comment by Griffinov22** [comment]
Thank you @matslina for your help. I fixed the image, and made getting the year dynamic, and corrected my app folder mistake. Do I need to make a new PR?

**Comment by Griffinov22** [comment]
I made changes that have passed all the requirements up until someone merges. Do I just need to wait again, or is there more steps I need to do to prepare my PR?

**Pull request closed without merging**
