### PR TITLE
New App: Bgg Last Play

### PR DESCRIPTION
**Pull request by DanDobrick**
Simple app that displays the number of days since the last time the given user has recorded a play on board game geek; I eventually want to pretty it up a bit, but this is a good first iteration.

bgg_last_play

### CODE REVIEW

**Comment by DanDobrick** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by dtsch** [comment]
@DanDobrick, I'm excited to see this app get submitted! I just made my first one yesterday, a very simple 'N days since X' display. My idea was to make that app to get an idea of how to work with Pixlet and everything, and then move onto making **exactly** what you just submitted.

Now I'll see if I can learn from Henry So Jr's BGGHotness app and combine it with your effort here to display box art and title of the last game played on a user's BGG account.

**Comment by DanDobrick** [comment]
> @DanDobrick, I'm excited to see this app get submitted! I just made my first one yesterday, a very simple 'N days since X' display. My idea was to make that app to get an idea of how to work with Pixlet and everything, and then move onto making **exactly** what you just submitted.
> 
> Now I'll see if I can learn from Henry So Jr's BGGHotness app and combine it with your effort here to display box art and title of the last game played on a user's BGG account.

That's a great idea! I want to make this app look nicer anyway, so it may be good to collaborate and integrate whatever you come up with into this app instead of having multiple bgg "last play" apps

**Comment by dtsch** [comment]
> @DTSH That's a great idea! I want to make this app look nicer anyway, so it may be good to collaborate and integrate whatever you come up with into this app instead of having multiple bgg "last play" apps

Yeah, absolutely, I meant building on top of this, though I didn't articulate it. I'll start chipping away at it, once this PR is approved and if I've made any progress I'll let you know and potentially submit another PR.

**Pull request merged**
