### PR TITLE
First run of new goldpriceticker app

### PR DESCRIPTION
**Pull request by aaronbrace76**
This is an app that can pull quotes for precious metals and display change since closing in absolute and percentage terms, as well as a graph. Its similar to the built in stock app provided by Tidbyt, but focused on precious metals. Screenshot is included.

It handles silver, gold, palladium and platinum.

### CODE REVIEW

**Comment by aaronbrace76** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by aaronbrace76** [comment]
recheck

**Comment by matslina** [comment]
Hey @aaronbrace76. Thanks for the PR. Build is failing due to your app not being registered in `apps/apps.go`.

**Comment by aaronbrace76** [comment]
Sorry, didn't realize make app updated that file. I just did another commit. Sorry for the rookie mistake!

**Pull request merged**
