### PR TITLE
New App: OS Runescape Grand Exchange

### PR DESCRIPTION
**Pull request by blakekwehrle**
# Description
Shows current item information from Old School Runescape's Grand Exchange. Items are cached for 7 days. There are about 4000 items.

gif4
gif2

# Copilot

### Summary
📄🎮📊

This pull request adds a new app for the Tidbyt device, called Runescape, which displays information about items from the Old School Runescape game. The app consists of a manifest file `apps/runescape/manifest.yaml` and a Starlark script `apps/runescape/runescape.star` that uses the Tidbyt API modules. The app fetches and caches item data from the Runescape API, and renders it using various layout widgets and base64 encoding.

> _`Runescape` app code_
> _Shows items from Grand Exchange_
> _Autumn of nostalgia_

### Walkthrough
* Create and implement a new app for displaying Runescape items on the Tidbyt device ([link](https://github.com/tidbyt/community/pull/1978/files?diff=unified&w=0#diff-9570d7d0a32b765e92ba6bc51ed6ba6565613d8c01c9dfdba79acd1939cb9df4L1-R7), [link](https://github.com/tidbyt/community/pull/1978/files?diff=unified&w=0#diff-4ae80e5e6a513d496ae56d39deb57aec15aa0fdbf96d63d7fb9f0875ec22ac1bL1-R95))
  - Add a manifest file `manifest.yaml` with the app metadata and configuration ([link](https://github.com/tidbyt/community/pull/1978/files?diff=unified&w=0#diff-9570d7d0a32b765e92ba6bc51ed6ba6565613d8c01c9dfdba79acd1939cb9df4L1-R7))
  - Add a Starlark script `runescape.star` with the app logic and rendering ([link](https://github.com/tidbyt/community/pull/1978/files?diff=unified&w=0#diff-4ae80e5e6a513d496ae56d39deb57aec15aa0fdbf96d63d7fb9f0875ec22ac1bL1-R95))
    * Import modules from the Tidbyt API such as `render`, `layout`, `random`, and `base64` ([link](https://github.com/tidbyt/community/pull/1978/files?diff=unified&w=0#diff-4ae80e5e6a513d496ae56d39deb57aec15aa0fdbf96d63d7fb9f0875ec22ac1bL1-R95))
    * Define constants and helper functions for the app settings, data processing, and caching ([link](https://github.com/tidbyt/community/pull/1978/files?diff=unified&w=0#diff-4ae80e5e6a513d496ae56d39deb57aec15aa0fdbf96d63d7fb9f0875ec22ac1bL1-R95))
    * Fetch and decode item data from the Runescape API using `http` and `base64` modules ([link](https://github.com/tidbyt/community/pull/1978/files?diff=unified&w=0#diff-4ae80e5e6a513d496ae56d39deb57aec15aa0fdbf96d63d7fb9f0875ec22ac1bL1-R95))
    * Select a random item and page from the cached data using `random` module ([link](https://github.com/tidbyt/community/pull/1978/files?diff=unified&w=0#diff-4ae80e5e6a513d496ae56d39deb57aec15aa0fdbf96d63d7fb9f0875ec22ac1bL1-R95))
    * Render the item sprite, name, price, and trend icon using `render` module and `layout` widgets ([link](https://github.com/tidbyt/community/pull/1978/files?diff=unified&w=0#diff-4ae80e5e6a513d496ae56d39deb57aec15aa0fdbf96d63d7fb9f0875ec22ac1bL1-R95))

### CODE REVIEW

**Comment by blakekwehrle** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by blakekwehrle** [comment]
image
currently app takes ~680 ms to load. May have to find a way to tweak the get's in get_cachable_data() though I'm not exactly sure how.

**Comment by blakekwehrle** [comment]
Just a additional note on that occasionally I see `pixlet check -r runescape ` take as long as a full second to render. I plan to do more and take a peek at the strava applet to see if that helps me crack this.

**Comment by matslina** [comment]
Hey! The problem is in the HTTP calls taking too long to complete. I think we'll have to nudge up the runtime limit a bit, as there are a few other very reasonable apps failing CI due to it.

**Pull request merged**
