### PR TITLE
New app: Reading Now

### PR DESCRIPTION
**Pull request by diegomura**
# Description
Displays Goodreads currently reading books and progress.

reading_now

### CODE REVIEW

**Comment by diegomura** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by diegomura** [comment]
Ci seems to be failing do to `delay` argument on Marquee widget. It's not documented, but it works as expected. Maybe should be added? Thanks in advance

**Comment by diegomura** [comment]
@betterengineering @matslina any chance you can take a look? 😄 🙏🏻  Thanks in advance

**Comment by matslina** [comment]
Hey. The delay flag on Marquee is in a newer version of Pixlet than what's currently used in the community repo. We'll bump that version soon, which should hopefully resolve this!

**Comment by diegomura** [comment]
Huh. @matslina should I open this again? Will be merge in a timely manner if I do?

**Pull request closed without merging**
