### PR TITLE
[feature-request] Shorter shortnames for goodservice app

### PR DESCRIPTION
**Pull request by connernilsen**
This PR adds shorter shortnames for Goodservice. Instead of displaying the name of the last station on the route, a configuration is provided to allow for setting the short name to "Uptown" or "Downtown". This PR also slows down the scrolling motion when displaying stations to make reading easier for users.

### CODE REVIEW

**Comment by connernilsen** [comment]
I'm going to be looking into the failing check, but I want to get the review process started on this so I'm opening it up to reviews.

**Comment by rs7q5** [comment]
Looks like you're erroring out because `inputText` is not a free fontAwesome icon.

**Comment by connernilsen** [comment]
> Looks like you're erroring out because `inputText` is not a free fontAwesome icon.

Thanks for that, @rs7q5! I thought I changed that when I last amended the diff, but it looks like it didn't go through 🙃

**Comment by matslina** [comment]
@blahblahblah- any opinions on this one?

**Comment by blahblahblah-** [comment]
Unfortunately, "Uptown" and "Downtown" really only makes sense within Manhattan and also does not work on the crosstown lines (i.e. 7, L, S), so I would prefer to use borough-based destinations or by cardinal direction (I prefer the former).

**Comment by connernilsen** [comment]
Thanks for the feedback, @blahblahblah-! I've gone through and set the destination to be the capitalized direction instead.

**Comment by betterengineering** [comment]
Thanks for the change @connernilsen! @blahblahblah- raises legitimate concerns. A Southbound 7 train would be nonsensical :sweat_smile:. I'm going to close this, but if you really wanted this type of change we could maybe support another app?

**Comment by blahblahblah-** [comment]
I may revisit this in the future to have borough-based direction names using the geolocation of the station in the future, since that would require adding more information to the API.

**Comment by blahblahblah-** [comment]
Actually @connernilsen, I'm open to merging the PR as it currently stands, if you would make certain lines be be "East" and "West" instead. Specifically 7, L, and GS.

**Pull request closed without merging**
