### PR TITLE
Update shabbat app

### PR DESCRIPTION
**Pull request by NudnikShpilkis**
Update the shabbat app for Tidbyt based on discussion with @dinosaursrarr .

### CODE REVIEW

**Comment by NudnikShpilkis** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by NudnikShpilkis** [comment]
> 



> **CLA Assistant Lite bot:** Thank you for your submission, we really appreciate it. Like many open-source projects, we ask that you all sign our [Contributor License Agreement](https://github.com/tidbyt/community/blob/main/docs/CLA.md) before we can accept your contribution. You can sign the CLA by just posting a Pull Request Comment same as the below format.
> 
> _**I have read the CLA Document and I hereby sign the CLA**_
> 
> **1** out of **2** committers have signed the CLA.✅ @NudnikShpilkis❌ @isaac Haberman**Isaac Haberman** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).You can retrigger this bot by commenting **recheck** in this Pull Request

Not sure why it's looking for Isaac Haberman.  That's me.  I don't use my name anywhere.

**Comment by NudnikShpilkis** [comment]
@betterengineering @matslina any ideas why the CLA Assistant is looking for the wrong user?

**Comment by matslina** [comment]
@NudnikShpilkis Looks like the first commit is authored by `ihaberman@roku.com`. Try adding that email address to your github account.

**Comment by NudnikShpilkis** [comment]
> @NudnikShpilkis Looks like the first commit is authored by `ihaberman@roku.com`. Try adding that email address to your github account.

That's what I get for using my work laptop 🤦

**Comment by matslina** [comment]
@NudnikShpilkis I noticed some schema fields are changing values in this change. E.g., `end_time` used to have an option `"RABBEINU_TAM"`, which now appears to be replaced with `"rabbeinu_tam"`. This means that all current users of the app will start seeing errors, as their installations of the app are set up to pass in the old values. We either need to stick with the old values (but can still change the `display` field, i.e. the name of of the field), or provide a translation from the old values to the new values, as you see fit.

**Comment by NudnikShpilkis** [comment]
> @NudnikShpilkis I noticed some schema fields are changing values in this change. E.g., `end_time` used to have an option `"RABBEINU_TAM"`, which now appears to be replaced with `"rabbeinu_tam"`. This means that all current users of the app will start seeing errors, as their installations of the app are set up to pass in the old values. We either need to stick with the old values (but can still change the `display` field, i.e. the name of of the field), or provide a translation from the old values to the new values, as you see fit.

Got it.  I'll add some code to translate the old values into the new ones.

**Comment by betterengineering** [comment]
Hey @NudnikShpilkis! Thanks for the changes! The issue is, there is a commit in this PR that was authored using your work account. The best path forward is to rewrite history to remove that commit or update the author of that commit to your personal account. I'd be a bit more comfortable bypassing it if it wasn't your work account that would have commits in this repo without signing the CLA. Please remove or modify the commit with your work account and we'll be happy to merge.

**Pull request closed without merging**
