### PR TITLE
Fix: Shopify sales_trends - fix for extra html and new cache system

### PR DESCRIPTION
**Pull request by jvivona**
# Description
Shopify counters have added new html into response json, removed via replace functions
updated app to use new cache and removed need for cache module

# Copilot

### Summary
🚀🧹📈

Improved sales trends app by using HTTP cache and removing HTML tags from `api_fetch`.

> _Oh we're the crew of the sales trends app_
> _And we fetch the data from the API_
> _We use the cache and we strip the tags_
> _To make it faster and prettier to see_

### Walkthrough
*  Removed cache module and used HTTP headers for caching ([link](https://github.com/tidbyt/community/pull/1682/files?diff=unified&w=0#diff-000214cb610f8ae2898dc65b01e79c71f04c964f5bcba8138b887ae5e8eb11e6L8-R15), [link](https://github.com/tidbyt/community/pull/1682/files?diff=unified&w=0#diff-000214cb610f8ae2898dc65b01e79c71f04c964f5bcba8138b887ae5e8eb11e6L203-R216))
*  Fixed bug where HTML span tags were added to amounts by API ([link](https://github.com/tidbyt/community/pull/1682/files?diff=unified&w=0#diff-000214cb610f8ae2898dc65b01e79c71f04c964f5bcba8138b887ae5e8eb11e6L8-R15), [link](https://github.com/tidbyt/community/pull/1682/files?diff=unified&w=0#diff-000214cb610f8ae2898dc65b01e79c71f04c964f5bcba8138b887ae5e8eb11e6L282-R280))
*  Documented changes and date in comment block ([link](https://github.com/tidbyt/community/pull/1682/files?diff=unified&w=0#diff-000214cb610f8ae2898dc65b01e79c71f04c964f5bcba8138b887ae5e8eb11e6L8-R15))
*  Added TODO comment for possible future conversion to new HTTP cache system ([link](https://github.com/tidbyt/community/pull/1682/files?diff=unified&w=0#diff-000214cb610f8ae2898dc65b01e79c71f04c964f5bcba8138b887ae5e8eb11e6L203-R216))

### CODE REVIEW

**Comment by jvivona** [comment]
@jnormore  - I fixed the issue where the counter API is now returning extra html in the post response + I updated it for the new caching system.   Let me know if there's anything you see that I didn't account for.

**Comment by jnormore** [comment]
Oh, nice catch! I’m going to update the counter api to render that html server-side before returning it to the tidbyt app though instead. Give me a couple hours and I’ll get that shipped!

**Comment by jnormore** [comment]
Or stripe it server-side, probably not going to render

**Comment by jvivona** [comment]
let me know & I can test on my end as well - I'll revise my code as needed.  we still needed to update the app for the new cache system - so we can at least keep that part.

**Comment by jnormore** [comment]
@jvivona ok it's live now

And yes, using the new cache system is a good call, thanks!

**Comment by jvivona** [comment]
@jnormore - thanks.  Didn't realize you were part of the API team for counter.  appreciate the quick fix - trying to roll this out for a client of ours.

**Comment by jvivona** [comment]
:shipit:

**Comment by jvivona** [comment]
reopen please

**Pull request merged**
