### PR TITLE
New App: DaysToXmas - Dev Version 1.0 Initial Build

### PR DESCRIPTION
**Pull request by mgodfrey10**
DaysToXmas - Dev Version 1.0 Initial Build

Display a countdown of days left til Christmas Day.

### CODE REVIEW

**Comment by mgodfrey10** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by matslina** [comment]
@mgodfrey10 Hey! Rebase on master and you should make it past the latest test failure.

**Comment by mgodfrey10** [comment]
Thanks @matslina - that worked and looks like the Pull Request is passing all the checks and builds. Please let me know if anything else is needed.

**Comment by matslina** [comment]
LGTM!

**Pull request merged**
