### PR TITLE
New app: Bluesky Stats

### PR DESCRIPTION
**Pull request by danielsitnik**
This app shows some statistics from the [Bluesky](https://bsky.social/) social network such as total number of users, follows, posts and likes.

Preview:
bluesky

### CODE REVIEW

**Comment by saltedlolly** [comment]
Thanks for building this. @matslina i hope this can be merged quickly as it would be great to have this week when Bluesky is seeing meteoric growth.

**Comment by saltedlolly** [comment]
I'm ever hopeful this will be merged soon. I keep checking every few days and no movement.

**Comment by danielsitnik** [comment]
Yep, very sad that this has been open for 2 weeks now. :(

**Comment by saltedlolly** [comment]
Merged finally!

**Comment by danielsitnik** [comment]
@matslina not sure what happened here but the app was merged to the root folder of the repo instead of being inside the `app` folder! 😮 

<kbd>image</kbd>

**Pull request merged**
