### PR TITLE
Divvy chicago bike app

### PR DESCRIPTION
**Pull request by wilcot**
Displays how many bikes are available at a Divvy station in Chicago

### CODE REVIEW

**Comment by wilcot** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by wilcot** [comment]
recheck

**Comment by wilcot** [comment]
Hmm I'm not sure why my build is failing. When I run `make lint` locally I'm not seeing errors. Does anyone have any insight to what is causing [this](https://github.com/tidbyt/community/runs/8197793105?check_suite_focus=true) to fail?

**Comment by dja852** [comment]
@wilcot If you go into Details on the lint it will show you the changes you should make which seem to be replacing single quotes '' with double quotes "", some spacing, and some missing commas

**Comment by andjosh** [comment]
Bump to @wilcot 
I'd use this one!

**Pull request closed without merging**
