### PR TITLE
chore(nightscout): Pass token using `Api-Secret` header

### PR DESCRIPTION
**Pull request by gabe565**
# Description
This PR changes the Nightscout app to pass a configured token using the `Api-Secret` header instead of using the `token` query param. This is safer since URLs are often kept in access logs.

This header is documented in Nightscout's [Swagger doc](https://petstore.swagger.io/?url=https://raw.githubusercontent.com/nightscout/cgm-remote-monitor/master/lib/server/swagger.yaml).

I have tested this against my own instance.

# Copilot

### Summary
🔒🔄📄

Improved security and compatibility of Nightscout app by using `Api-Secret` header for authentication. Modified `apps/nightscout/nightscout.star` to send the header with `http.get`.

> _To access the Nightscout API_
> _The old way was not very spry_
> _So they added `headers`_
> _To avoid any wedges_
> _And used `Api-Secret` to fly_

### Walkthrough
*  Use `Api-Secret` header for authentication with Nightscout API ([link](https://github.com/tidbyt/community/pull/2065/files?diff=unified&w=0#diff-76126fb2f5f6edd57d467ea196a5537f9f0f062d734669d13d9fa5c63bc7fdd4L819-R821), [link](https://github.com/tidbyt/community/pull/2065/files?diff=unified&w=0#diff-76126fb2f5f6edd57d467ea196a5537f9f0f062d734669d13d9fa5c63bc7fdd4L827-R828))

### CODE REVIEW

**Comment by gabe565** [comment]
@IsThisPaul If you get a chance, would you mind testing this PR against your instance?

**Comment by gabe565** [comment]
@IsThisPaul No problem! I tested against my instance which requires tokens, and everything is working well. I just thought you'd like to verify 🙂

**Comment by gabe565** [comment]
@IsThisPaul This is just another way to pass the token. All instances support the query param and the header, and just like before it is excluded if not set.

**Comment by matslina** [comment]
LMK if/when this should be merged. @IsThisPaul

**Comment by gabe565** [comment]
@matslina It's ready to be merged!

**Comment by IsThisPaul** [comment]
I have not had the chance to review this but trust Gabe’s testing.

—
Paul

**Comment by IsThisPaul** [comment]
I just received a report of a NS 401 error from a user with a NS token. Did
the old method break?

—
Paul

**Comment by gabe565** [comment]
Interesting. I checked Nightscout source and `Api-Secret` has been supported for years, so I'm unsure why some users get a 401. For now, I can add a fallback to the old method if a 401 is returned.

**Pull request merged**
