### PR TITLE
New App: Is it Friday the 13th?

### PR DESCRIPTION
**Pull request by griffeth**
This PR will create (when development is complete) a new app called, "Is it Friday the 13th?"

This is based on the existing app, "Is it Christmas?" authored by @austinrfnd and this variation is inspired by [/r/IsTodayFridayThe13th](https://www.reddit.com/r/IsTodayFridayThe13th/) on Reddit.

Displayed:

- "Is it Friday the 13th?" potentially in some "spooky" font?
- "Yes/No"
- Image of a hockey mask and a machete

### CODE REVIEW

**Comment by griffeth** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by griffeth** [comment]
Changing the PR to draft so I can work on it without triggering anything. I may end up closing this PR to work locally and then when things are ready, I can open a new PR.

**Comment by austinrfnd** [comment]
@griffeth this is great! Let me know if you need any help! Also please let me know any improvements you may make and I can backfill to my app.

**Comment by griffeth** [comment]
@austinrfnd - I used my work GitHub account originally to open this PR but I'm now using my personal account @griff-brand to work on it.

**Pull request closed without merging**
