### PR TITLE
New NES Clock

### PR DESCRIPTION
**Pull request by hx009**
P

# Description
A quick NES Game Themed Clock applet

# Copilot

copilot:all
nes_clock

### CODE REVIEW

**Comment by hx009** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by hx009** [comment]
recheck

**Comment by hx009** [comment]
recheck

**Comment by hx009** [comment]
Can someone manually bypass the CLA assistant?  I read and signed the CLA but the bot will not pass even after recheck.

**Comment by hx009** [comment]
_I have read the CLA Document and I hereby sign the CLA_

**Comment by hx009** [comment]
recheck

**Comment by hx009** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by hx009** [comment]
_I have read the CLA Document and I hereby sign the CLA_

**Comment by hx009** [comment]
@matslina The CLA Assistant job passed for this PR here:

https://github.com/tidbyt/community/actions/runs/7543793948

but the checks above is still listing it as failed for some reason?

**Comment by hx009** [comment]
recheck

**Comment by M0ntyP** [comment]
Hey @hx009 , I think its failing because the files were committed by someone else - @jsfromve . They need to also "sign the CLA"

That's my guess as to why its not passing

**Pull request closed without merging**
