### PR TITLE
Add Zmanim (Jewish Prayer Times)

### PR DESCRIPTION
**Pull request by shimonsavitsky**
Add Zmanim App

This app displays Jewish prayer times (zmanim) based on user location:
- Customizable by ZIP code
- Shows all important daily prayer times
- Clear display with highlighted times
- Vertical scrolling display
- Data from Chabad.org API

Tested locally and verified working with multiple ZIP codes.

### CODE REVIEW

**Comment by shimonsavitsky** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by shimonsavitsky** [comment]
review

**Comment by matslina** [comment]
Hey. Please remove the .star file in the root of the repo. All app files need to live under `apps/`.

**Comment by shimonsavitsky** [comment]
@matslina done

**Pull request merged**
