### PR TITLE
Update: MiLB Scores

### PR DESCRIPTION
**Pull request by M0ntyP**
# Description
Changed the names on the league selection dropdown

# Copilot

copilot:all

### CODE REVIEW

**Comment by M0ntyP** [comment]
recheck

**Comment by jmanske** [comment]
@matslina any thought to being able to grandfather in apps like this past the 1000 ms rendering limit? If you can show the changes do not effectively increase the rendering time, there is not a good reason I think to deny the PR when it fixes a real bug.

#2346 has the same problem.

**Comment by M0ntyP** [comment]
recheck

**Comment by matslina** [comment]
Hey, sorry for the tremendous delay on this.

Yeah, I think we need something like that. Plenty of apps have acceptable performance, except on the very first run before cache is warmed up.

**Comment by matslina** [comment]
Temporarily bypassed the runtime check for this one.

**Pull request merged**
