### PR TITLE
New App: Chess Viewer

### PR DESCRIPTION
**Pull request by Hendeca**
# Chess Viewer App for Tidbyt

Displays currently active games from [Chess.com](chess.com) for the username provided. If no username is provided, the app shows famous chess games from history. The chess piece graphics can be changed via the Piece Theme setting and the board graphics can be changed via the Board Theme setting. The king piece for each side has a special color added to distinguish it from the other pieces. The "minim" piece theme is the default theme and is considered to be the most readable on the Tidbyt. The player whose turn it is to move has an asterisk next to it. The advantage in material in points is shown next to each color:

## Piece Values in Chess
* Pawn: 1 point
* Knight: 3 points
* Bishop: 3 points
* Rook: 5 points
* Queen: 9 points

## Available Board Themes:
* Summer (default) - Reddish orange
* Fall - Brown
* Winter - Blue
* Spring - Green

## Available Piece Themes:
* Minim (default) - Most readable and intuitive.
* Block - A variation on the Minim theme.
* Dot - All shapes start in the upper left of the square to prevent confusion when two pieces are next to each other.
* Point - Abstract theme that matches each piece with its point value. The number of pixels in each piece design is equal to its material point value. The king has a total of 10 pixels but can be distinguished by its special color dot.

The name shown is the opponent's username as well as what color that user is playing in the game shown.
Enjoy!

chess_viewer

### CODE REVIEW

**Comment by Hendeca** [comment]
Oh, just realized the OGS Games Viewer app files are included in this merge, not sure why. I'm still a bit new to the PR process

**Comment by matslina** [comment]
> Oh, just realized the OGS Games Viewer app files are included in this merge, not sure why. I'm still a bit new to the PR process

This is a bit finnicky for sure. It looks like your chess changes were made in the same branch as your OGS changes, without rebasing after the OGS PR got merged.

The app itself looks good though. Happy to merge it when the OGS changes are removed!

**Comment by Hendeca** [comment]
> This is a bit finnicky for sure. It looks like your chess changes were made in the same branch as your OGS changes, without rebasing after the OGS PR got merged.

Ok I think I've fixed it. Sorry about that, the PR workflow is still a bit new to me. Please let me know if I did it incorrectly, but it seems that the OGS files are no longer shown as part of this PR.

Thank you!

**Comment by matslina** [comment]
Sweet! Thank you for the PR!

**Pull request merged**
