### PR TITLE
added gradient clock app

### PR DESCRIPTION
**Pull request by tpatel12**
Created a simple clock app with animated background gradient. Hope to publish!
gradient_clock

I have read the CLA Document and I hereby sign the CLA.

### CODE REVIEW

**Comment by tpatel12** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by tpatel12** [comment]
recheck

**Comment by kaffolder7** [comment]
Hi @tpatel12, just some friendly advice. Looks like you have a `gradient_clock.star` file in the root of your fork. I believe the approach the Tidbyt team takes is to ensure that any community apps are only contributed in the `/apps/<yourappname>` folders. I see that another contributor already has a gradient clock contributed to `/apps/gradientclock`, so you will need to pick another app/folder name as to not override their community app. (e.g. `/apps/gradientclock2` or some other equivalent)

Also, as a part of your app folder, let's say `/apps/gradientclock2`, for example, you will need to also add a `/apps/gradientclock2/manifest.yaml` file. Please follow documentation (or another app contributor's manifest file) to better understand how to create & format this file. 😊

**Comment by tpatel12** [comment]
Thanks for the advice @kaffolder7! I've restructured my project as you suggested, please let me know if anything else is needed!

**Pull request merged**
