### PR TITLE
Add Arcade Classics app

### PR DESCRIPTION
**Pull request by sotteson1**
Adds an app that shows two different animation options, selectable via an option:

- Pac-Man and Ms. Pac-Man chasing and getting chased by ghosts.
- Space Invaders march back and forth.

The animations are randomly generated using the current minute as the seed. There is a single config option for setting the speed of the animations.

I will probably add a third animation in the future, but more could be added too.

pacman

spaceinvaders

### CODE REVIEW

**Comment by sotteson1** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by rs7q5** [comment]
Was thinking about doing this with mario or zelda!

**Comment by sotteson1** [comment]
I'm thinking about combing this with another one I've made, so that you can choose which amination(s) you want it to show.

**Comment by rs7q5** [comment]
Oh nice! just all of the video games!

**Comment by fxb** [comment]
I love this!

**Review by betterengineering — APPROVED** [review]
This is rad! Super excited to see this on my Tidbyt

**Comment by betterengineering** [comment]
The failure here is unrelated, merging

**Pull request merged**
