### PR TITLE
Bug Fixes

### PR DESCRIPTION
**Pull request by rjison**
Display the next future date, skip past items. Remove cache for now.

### CODE REVIEW

**Comment by tavdog** [comment]
you should not remove data caching.

**Comment by rjison** [comment]
> you should not remove data caching.

I noticed that my Tidbyt was displaying information based on someone else's settings. I don't know how that would be possible, but the only thing I could think of is the cache was server side and the XML I cached, was then overwritten by someone else.

That's why I removed it. Do you think I'm wrong here?

**Comment by tavdog** [comment]
> 
The data caching is needed to keep the cloud costs low.  Without caching, every install of your app will pull the xml data every time it updates ( around every 5 minutes or so ).  This is at a time when they are trying to dial back on their cloud costs too.  

I made an edit to your code to use a location unique cache key.  It started working for most users after that.  I'm not sure if your stale data was caused by the non-unique caching problem or something else.  The current cache key is based on the full xml url which I assume is ok unless there is a character limit for the cache key.  In that case it would probably be best build the cache key based on just the last part of the url (eg.  "United_States_Florida_Orland.xml" )

**Comment by rjison** [comment]
Does anyone have some advice for getting this last test to pass?

**Comment by brandontod97** [comment]
Apparently they seem to be aware of other apps causing your PR to fail (which from what I saw seems to be your issue). So hopefully they'll resolve it soon. I'm not sure how others are seemingly avoiding the issue altogether though.

**Comment by rjison** [comment]
@rohansingh Any advice to get this to pass the tests?

**Comment by rohansingh** [comment]
Could you please rebase on `main`?

**Pull request merged**
