### PR TITLE
Added IOB option in place of clock plus bug fix

### PR DESCRIPTION
**Pull request by JimAdkins**
# Description
Added option to show current Insulin on Board in place of Clock. Also bug fix for newer version of NS which does not use "dateString" in entries JSON.

# Copilot

copilot:all

### CODE REVIEW

**Comment by JimAdkins** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by matslina** [comment]
I believe part of the motivation for including a clock is to demonstrate that the data on display is up to date?

**Comment by IsThisPaul** [comment]
There’s separate functionality to show the age of the blood sugar data. The
clock is merely a novelty.

—
Paul

**Comment by IsThisPaul** [comment]
IOB is a good addition.

—
Paul

**Comment by IsThisPaul** [comment]
I would prefer to see the whole reading moved to api v2 instead of just the
iob reading. In this PR there are now 2 JSON reading instead of 1. Am I
seeing that right?


—
Paul

**Comment by IsThisPaul** [comment]
We need to be sure to update the description and version number in both the
yaml and the star files.

Is there also a fix for the threshold values not working in these bug
fixes?

—
Paul

**Comment by JimAdkins** [comment]
Hello Paul, firstly, thank you so much for reviewing my PR. This is my first time dabbling in Tidbyt, I bought 2 after seeing your interview with Diabetech on YouTube. I was excited to get them, but then found that I couldn't get my version of NS (v15) to work in the app. I'm not a python expert, but have fooled around with it in the past, so I set off trying to fix my issue. The past couple of days I've been playing with the code. 

As for the clock, that option/code is still there. I merely added a drop down to select if you want to show the clock/IOB. 

You are correct, I am doing 2 API calls, and I just realized that I'm not checking to see if IOB is selected before calling that in the code. This is a mistake, and I will work on fixing that today. 

I'm also happy to play with the V2 API and see what it would take to move to it. I might be able to just make 1 call for readings and IOB. I'm not super familiar with the NS API options, but happy to dig into it. 

"Is there also a fix for the threshold values not working in these bug fixes?" - I'm not aware of these issues as I haven't successfully gotten the tidbyt to display my NS values. Outside of playing with pixlet, and rendering in FireFox, I'm not sure how else to test. The bug I found with my NS installation was the "dateString" field is not in my entries JSON. I added a line to check for dateString, and if it's not there, to try "created_at" which is present in my NS v15 deployment. 

Please let me know if there is anything else I might be able to help with. Also, THANK YOU for spending so much time working on and deploying this option for those of us with T1D in our lives. My son was diagnosed nearly 4 years ago, and finding NS, AAPS, as well as this has been life changing.

**Comment by IsThisPaul** [comment]
I haven’t fooled with the v2 API much either.

Let’s move this conversation to email.
Email me directly ***@***.*** and let’s collaborate.

Let’s close this PR and resubmit when we have this sorted out.

—
Paul

**Comment by JimAdkins** [comment]
It obfuscated your email address. Try me: uptome25 at gmail dot com.

**Comment by JimAdkins** [comment]
Closing this for now. Thanks!

**Pull request closed without merging**
