### PR TITLE
EPL App: Reverse home and away teams

### PR DESCRIPTION
**Pull request by jeremycohen**
## Description
Home team is listed before away team for non North American sports.

Sources: https://en.wikipedia.org/wiki/Home_(sports)#Miscellaneous, https://www.espn.com/soccer/scoreboard/_/date/20231215/league/eng.1, https://www.espn.com/soccer/scoreboard/_/date/20231210/league/eng.1 (notice how order of these scores matches test plan)

Note this is the same as https://github.com/tidbyt/community/pull/2108 but had some issues with signing the CLA I had to run through before signing now.

## Test Plan
Render pre-game and post-game scoreboards with change.

See https://github.com/tidbyt/community/pull/2108#issue-2037838113 for the test plan executed for this.

### CODE REVIEW

**Comment by matslina** [comment]
@mabroadfo1027 Thoughts?

**Comment by mabroadfo1027** [comment]
go for it

**Comment by jeremycohen** [comment]
Thanks. @matslina can you pls merge when you have a chance?

**Comment by matslina** [comment]
@jeremycohen Sorry would've merged sooner, but didn't see your comment until now. Been heads down on Gen 2 firmware for the past few weeks.

**Pull request merged**
