### PR TITLE
Add Multi-Calendar App

### PR DESCRIPTION
**Pull request by logandeal**
# Description
This adds a new multi-calendar app. The app displays the next event (within the next 24 hours) on one or more Google calendars. By default, it grabs the next event from all of a user's calendars when no Google Calendar IDs are specified. Optionally, a user may specify a comma-delimited list of Google Calendar IDs that the app will use when displaying the next event. If there is no event in the next 24 hours, it simply tells the user that there are no events in the next 24 hours. When the current time is more than half past the current event's duration, the next event will be displayed.

This app also supports 12 and 24-hour time.

# Copilot

copilot:all

### CODE REVIEW

**Comment by logandeal** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by logandeal** [comment]
@matslina Is there an issue with the code?

**Comment by logandeal** [comment]
Sample Gif
Tidbyt

**Comment by matslina** [comment]
@logandeal Thanks for the PR, and apologies for the delay. We've had a very busy couple of weeks, and all PRs have suffered as a consequence. Especially less trivial ones.

And I'm afraid this PR is not entirely trivial. I'll do my best to test it out over the next few days. We'll need to migrate the app to use Tidbyt's oauth2 credentials, which (sometimes) cascades into a painful review process with Google. Now that I look at it, I think we already have these scopes covered, which means it might be fairly straightforward. Stay tuned, and again, apologies for the delay.

**Comment by logandeal** [comment]
@matslina Any updates? I would really like to have this app get released so that we can all use multiple calendars!

**Comment by logandeal** [comment]
Keeping this open.

**Comment by kaffolder7** [comment]
Can we please keep this open? This would be _super_ helpful for us. @logandeal has done a lot of the legwork. 🥳

**Pull request closed without merging**
