### PR TITLE
New App: Los Angeles Metro Rail arrivals

### PR DESCRIPTION
**Pull request by talevy42**
This app lookups arrival predictions for la metro rail near a location. It requires the user to enter their own API key, as the official LA Metro API (swiftly) requires authentication and places limits on API usage.

### CODE REVIEW

**Comment by talevy42** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by talevy42** [comment]
recheck

**Comment by talevy42** [comment]
recheck

**Comment by talevy42** [comment]
Don't understand why the CLA assistant is still failing

**Comment by tal42levy** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by talevy42** [comment]
Recheck

**Pull request merged**
