### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by FrontierProphet**
Ive tried this so long ago, giving it one last go

### CODE REVIEW

**Comment by FrontierProphet** [comment]
App works fine locally when using my api key, having issues with secret api encryption

**Comment by FrontierProphet** [comment]
I got a tidbyt for christmas last year and made this in January, it has been haunting me ever since, please for the love of god help me get this to work someone

**Comment by theimpossibleleap** [comment]
Hey @FrontierProphet - Maybe this is your issue? https://discuss.tidbyt.com/t/secrets-decrypt-fails-request/6439/3

When I cloned the repo locally it's definitely returning "`None`" as the URL. I would check the suggestion in that thread and report back. Hope that helps!

**Comment by FrontierProphet** [comment]
much appreciated Ill give that another go

**Pull request closed without merging**
