### PR TITLE
Changed to vertical scroll and added Park&Ride

### PR DESCRIPTION
**Pull request by derekllaw**
# Description
Modified to vertical scroll and added logo

# Copilot

copilot:all

### CODE REVIEW

**Comment by matslina** [comment]
Thanks for the PR. There are some conflicts here that need to be resolved before merging. Could you rebase the PR? Alternatively, create a new fork of the community repo, reapply the changes there and cut a new PR?

**Comment by derekllaw** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by derekllaw** [comment]
recheck

**Comment by mokolodi1** [comment]
How to fix this:
```
git checkout 69c720291f50522cb2f70ecbdfec01593f442513 #  after your first few commits - you'll end up in headless mode
git checkout -b park-and-ride  # switch to a branch
git cherry-pick cd0f88b63d30b949b6ee046018fc3324e14b5e2a  # add the commits that you did later
git cherry-pick 22fb49dab7199d7254fefb1b62be95e2a53196d6
git cherry-pick 647ceff2abecd87b0296dcc12fb40d0965f8e512
git push origin park-and-ride  # push that new branch to your forked repo
```

Then either recreate a new PR from `derekllaw:park-and-ride` or fix `main` somehow (this is slightly sketch, but something like this should work: `git branch -D main`, `git checkout main` [should pull from origin], `git merge park-and-ride`)

**Pull request closed without merging**
