### PR TITLE
Removed API key and tidied up display

### PR DESCRIPTION
**Pull request by vipulchhajer**
# Description
Tidied up display

# Copilot

copilot:all

### CODE REVIEW

**Comment by vipulchhajer** [comment]
Hi @matslina Would you mind giving this is quick review?

**Comment by matslina** [comment]
Hey @vipulchhajer. This PR adds some files under `.idea` that I'd rather not merge into the repo. But the starlark changes are fine, happy to merge those!

**Comment by vipulchhajer** [comment]
Hi @matslina Thanks. The files under `.idea` seem like a mistake on my end. Yes, please merge the starlark changes. Let me know if I need to do anything.

**Comment by vipulchhajer** [comment]
hi @matslina Bumping this :) Mind merging in the starlark changes? Or let me know if there's something I need to do 🙏

**Pull request closed without merging**
