### PR TITLE
Initial Commit of Hanukkah App

### PR DESCRIPTION
**Pull request by BryanSlavinBryter**
# Description
My first Tidbyt app! I noticed that there wasn't an app to celebrate Hanukkah, so here is the first version.  There are several TODOs throughout with some changes I'd like to try to get in before Hanukkah starts Thursday evening, but this is a fully functioning first version in the event I don't get to the changes in time.

# Copilot

### Summary
🕎📅📝

This pull request adds a new applet for Hanukkah, which displays a menorah and a countdown on the Tidbyt device. It includes the main code file `hanukkah.star` and the manifest file `manifest.yaml` for the applet metadata.

> _`Hanukkah` applet_
> _Shows menorah and countdown_
> _Winter lights on `Tidbyt`_

### Walkthrough
* Create and register a new applet for Hanukkah ([link](https://github.com/tidbyt/community/pull/2089/files?diff=unified&w=0#diff-dbabb891494d814b3e6b4697b20da2f56d1fe2ac0ae34e0b94077e9488e16eebR1-R8), [link](https://github.com/tidbyt/community/pull/2089/files?diff=unified&w=0#diff-9820337f6a6ac538eafe3867cc035f8e344894b4c2bd957330f570a66a0b4e6aR1-R95))

### CODE REVIEW

**Comment by BryanSlavinBryter** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by BryanSlavinBryter** [comment]
recheck

**Comment by paultyng** [comment]
@matslina I'm sure you are pretty busy, but considering its the first night tonight, it would be cool to have this!

**Comment by matslina** [comment]
Happy Hanukkah y'all!

**Pull request merged**
