### PR TITLE
MN Metro Transit App

### PR DESCRIPTION
**Pull request by AmillionAirs**
Well...... we know how much you loved my original Minnesota Light rail app so buckle up boys cause now we got FULL ON BUS FUNCTIONALITY TOO!!!!

My buddy uses just the light rail in the summer, but in the winter time the 20 minute walk to the light rail stop is just to much for his little face to handle. So he then defaults to just getting on the bus that stops a block away from his house and riding to the stop instead. 

I'm submitting this app as a separate submission from the original light rail app I made as I only exclusively ride the light rail. Therefore, the original light rail app i made suits that need perfectly and is compact with only the info i need/want for it.

This new app I'm calling this the "MN Metro Transit" app as it encompasses everything within the Minnesota transit department offers (Bus and Train). This new app adjusts the look of the original app to accommodate for some of the longer naming conventions of the bus lines and also has some additional colors and directional features to go along with it.

https://user-images.githubusercontent.com/97411638/209259656-ecbc009e-8625-4c76-9356-9eed4695b407.mp4

### CODE REVIEW

**Comment by GE-Ninety** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by GE-Ninety** [comment]
recheck

**Comment by AmillionAirs** [comment]
For reference @GE-Ninety is the buddy I made this for. So will be nice to have him on here as co contributor in case things need to change in the future for the app.

**Comment by betterengineering** [comment]
Going to close this in favor of #919

**Pull request closed without merging**
