### PR TITLE
OPM Status for Tidbyt

### PR DESCRIPTION
**Pull request by AdamMoses-GitHub**
# OPM Status for Tidbyt [repeat of app readme.md]

Displays the current [OPM Status](https://www.opm.gov/policy-data-oversight/snow-dismissal-procedures/current-status/), e.g. the Office of Personnel Management status, which is used by federal employees to know if the normal working conditions have been changed by inclement weather, health hazards, or other alerts. Updates every 2 hours. No API key required.

Uses the OPM Status JSON feed at [https://www.opm.gov/json/operatingstatus.json](https://www.opm.gov/json/operatingstatus.json) for updates.

screenshot

### CODE REVIEW

**Comment by AdamMoses-GitHub** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by AdamMoses-GitHub** [comment]
Is there anything I can do, not sure why it failed the lint step.

**Comment by rs7q5** [comment]
did you run `make lint` or I guess `pixlet format` on this file? if not that may be the issue.

**Comment by AdamMoses-GitHub** [comment]
I didn't see "pixlet format" requirement but will run that ASAP. 

"make lint" failed but the obvious pathing issues mentioned in the docs didnt' fix it.

**Comment by rs7q5** [comment]
why did `make lint` fail?

**Comment by AdamMoses-GitHub** [comment]
It gave me that builidifer not found error mentioned in the docs but the fix there didn't work. Wondering if this is because I'm on windows, looks like most of the docs are for Mac or Linux.

**Comment by rs7q5** [comment]
You'd probably have to hunt down installing make or whatever on your end. but `pixlet format` should be equivalent. I would run `pixlet lint` too. But make sure you are on the most up to date version of pixlet. 

I just copy and pasted your code into a file and ran `pixlet format` and it looks like that is whythe lint build and test is failing. 

Also note, the `version` in `schema.Schema` should be 1, as it is not for our use. I think it is an internal parameter or something used for something, so will fail if it is not 1. 

Finally, if you don't have any schema, then you donn't need to pass `config` into main or need the `get_schema()`.

**Comment by AdamMoses-GitHub** [comment]
Okay, I'll dump the schema and the config pass-in and test it with pixel format.

**Comment by AdamMoses-GitHub** [comment]
`Error: unknown command "format" for "pixlet"
Run 'pixlet --help' for usage.
unknown command "format" for "pixlet"`

Is there a special build flag I need to get that to work?

**Comment by rs7q5** [comment]
If it doesn't have the `format` command, then you most likely need to update your version of pixlet.

**Comment by AdamMoses-GitHub** [comment]
Yea, that was the issue, I had two copies of the pixlet repo so that was causing problems.

Ran pixlet format, I think it's all good now.

**Comment by AdamMoses-GitHub** [comment]
How long does a review usually take?

**Comment by rs7q5** [comment]
It depends. They try to do them on Thursday's, but once it gets merged sometimes they do internal testing. Oauth apps can take longer. Think they've been busy improving pixlet and stuff to make dev stuff easier. May take a little bit to catch up after the holidays too. 

But nothing for you to do on your end if all checks have passed.

**Comment by matslina** [comment]
Thanks for the PR. Merged!

**Pull request merged**
