### PR TITLE
Applet: Daily Reminder

### PR DESCRIPTION
**Pull request by sepowitz**
Hello! Thanks for building this wonderful community. We had a need in our simple household to display a reminder for each day of the week, and thought other folks might too. 

Looking forward to you feedback.

### CODE REVIEW

**Comment by sepowitz** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by sepowitz** [comment]
recheck

**Comment by matslina** [comment]
Hey @sepowitz and thanks for the PR. Last time I saw this problem with the CLA it was due to the email address used making commits was not associated with the github account used. Could you check your github settings to make sure this email address is in there?

**Comment by sepowitz** [comment]
> Hey @sepowitz and thanks for the PR. Last time I saw this problem with the CLA it was due to the email address used making commits was not associated with the github account used. Could you check your github settings to make sure this email address is in there?

Hey @matslina just double checked and my email seems to be correctly configured and set as my primary email in my Github settings. Also, looks like my commits are being correctly attributed to my Github user. Anything else I can do to get the CLA Assistant check to pass? TY!

**Comment by sepowitz** [comment]
> > ... my email seems to be correctly configured and set as my primary email in my Github settings. Also, looks like my commits are being correctly attributed to my Github user. Anything else I can do to get the CLA Assistant check to pass? TY!
> 
> Including the sanctuary.computer one associated with the first commit ([e731847](https://github.com/tidbyt/community/commit/e731847b55d3bbc695b1461cd245798edcf7afc5)?)

Ah didn't see that. That is an old email (I no longer have access to) I updated my primary email in subsequent commits, but didn't seem to fix the problem. Should I close this and open a new PR?

**Comment by matslina** [comment]
> Ah didn't see that. That is an old email (I no longer have access to) I updated my primary email in subsequent commits, but didn't seem to fix the problem. Should I close this and open a new PR?

A new PR should do the trick. Another option might be to temporarily add that second email address to your Github account and requesting a recheck. Not sure if the latter will work but could be worth trying!

**Comment by sepowitz** [comment]
recheck

**Comment by sepowitz** [comment]
Nice! Looks like all checks passed 🟢

**Pull request merged**
