### PR TITLE
World Time: Added option for meridian time

### PR DESCRIPTION
**Pull request by mrmcpowned**
image

### CODE REVIEW

**Comment by mrmcpowned** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by mrmcpowned** [comment]
@ejb Think you could look this PR over and give it a signoff if it all looks good?

**Comment by ejb** [comment]
Thank you for the feature add @mrmcpowned! It’s a great addition. One question I have though: would it make more sense for this to be a global setting for all clocks?

**Comment by betterengineering** [comment]
+1 This is a great idea! Would love for it to be a single toggle for all three clocks though

**Comment by mrmcpowned** [comment]
I don't have any objections to having it as a single toggle.  My initial changes were more for the sake of configurability. I'll make the change later today and ask for a review then

**Comment by mrmcpowned** [comment]
image

Simplified the config so now all the clocks are in the same format when configured. @ejb @betterengineering feel free to review!

**Pull request merged**
