### PR TITLE
first commit of select.live app.

### PR DESCRIPTION
**Pull request by simonhac**
# Description
a pixlet app to remotely display the status of a Selectronic SP PRO inverter fetching data from select.live

select_live

# Copilot

copilot:all

### CODE REVIEW

**Comment by simonhac** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by simonhac** [comment]
recheck

**Comment by simonhac** [comment]
so, is this in your hands @matslina? (my first PR to this repo!)

**Comment by matslina** [comment]
Hey @simonhac. Yes, it is in my hands. Apologies for the terrible delay. We're really focused on Tidbyt Gen 2 functionality right now, and the community repo is unfortunately lagging behind a whole lot. Trying to catch up bit by bit.

If i understand this correctly, the app will (currently) pass data through your service (code included in the PR) hosted on replit? I think we can do that, but we'd need a _very_ clear explanation in the app description that lets users know their username and password will be passing through a 3rd party service hosted by you. And it'd need to be like, _very_ clear.

I'll try to take a look at the cookie discussion in the PR you linked sometime soon, but can't promise much because... Gen 2.

**Comment by simonhac** [comment]
thanks @matslina i'll have a go at writing that app description.

(i'm a bit of a git newbie, so will need to google around to work out how to update the PR.)

can't wait to get my hands on a Gen 2… though looks like it doesn't ship to australia :(

**Pull request closed without merging**
