### PR TITLE
updating with new Tap List app

### PR DESCRIPTION
**Pull request by bernie-thibeault**
# Description
Created an app to display up to 4 beers in a tap list

# Copilot

copilot:all

### CODE REVIEW

**Comment by bernie-thibeault** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by bernie-thibeault** [comment]
I read the CLA Document and I approve of it - do I need to do anything else to complete this PR?

**Comment by matslina** [comment]
recheck

**Comment by matslina** [comment]
Any chance the email address on the PR commits is different from what you have on your github account? Seen that confuse the CLA bot before.

**Comment by bernie-thibeault** [comment]
hmm - I know that I created my Github account with a different email, then changed it to this latest one. But I believe the emails should match for this given PR

**Pull request closed without merging**
