### PR TITLE
added r/place app to community apps

### PR DESCRIPTION
**Pull request by funkfinger**
Hi, here is a viewer that shows a tidbit of what was created for r/place 2022. It pulls the full r/place image and then animates a portion of the image across the Tidbyt screen. Pretty simple, but the r/place artwork pixel artwork really displays nicely on the device.

r_place_2022-doge

### CODE REVIEW

**Comment by funkfinger** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by funkfinger** [comment]
recheck

**Comment by funkfinger** [comment]
not sure where that second committer is coming from - my name is Jay Wiggins, but my Git handle is @funkfinger.

**Comment by rs7q5** [comment]
Do you have a second GitHub account? It's linking both of them. Both accounts with those emails associated need to sign the cla or to make things easier you should redo your git config on your computer and resubmit.

**Comment by funkfinger** [comment]
I'm going to close this to see if I can figure out the dual username issue - will re-submit soon...

**Pull request closed without merging**
