### PR TITLE
New App: Switchboard

### PR DESCRIPTION
**Pull request by bguggs**
This adds a new app, Switchboard. Switchboard provides tools for political organizations to run more effective campaigns. This is a v1 of the app that allows you to see your organization's in-app data on your Tidbyt.

Displayed:
- Switchboard Logo (Submitted on behalf of Switchboard Public Benefit Corp, all rights reserved)
- Top text populated via API: e.g. "Goal: $10k". Shows current time if not provided via API.
- Marquee text populated via API: e.g. "Raised $5,323.43"
- Bottom banner as a thermometer to show % to goal. Passed in as a pixel width via API.

### CODE REVIEW

**Comment by bguggs** [comment]
I have read the CLA Document and I hereby sign the CLA

However, the Logo image is submitted on behalf of a third-party: [Switchboard](https://oneswitchboard.com/)

**Comment by bguggs** [comment]
However, the Logo image is submitted on behalf of a third-party: [Switchboard](https://oneswitchboard.com/)

**Comment by bguggs** [comment]
recheck

**Comment by bguggs** [comment]
P.S. This app is intended primarily for Switchboard users (~20-100 devices total) not general consumption. If there is a better way to distribute the app to those users please lmk.

**Comment by matslina** [comment]
Thanks for the PR. If you ping me on Discord I can hook you up with beta access to test it all out in production, before we make it publicly available to all users. Heads up that I'll be out for most of next week though so thing may move a bit slower than normal.

**Pull request merged**
