### PR TITLE
Update Weather Snapshot to allow use of personal api key

### PR DESCRIPTION
**Pull request by elijahyoon**
Added personal API Key schema (config) value to allow more frequent updates (every 10 minutes vs every 6 hrs). Changed weather API to free tier that does not require a credit card. Original functionality is maintained if no personal API key is provided (will still use the provided hashed API keys in file and cache/query every 6 hrs).

### CODE REVIEW

**Comment by elijahyoon** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by elijahyoon** [comment]
I had to recreate my pull request due to an error committing code under the wrong user and being unable to sign the CLA with my second user.

@arieltian I reverted the AQI API to what it was previously and just added extra logic to handle caching differently if a personal API key is provided. Let me know what you think!

**Comment by matslina** [comment]
@arieltian Thoughts on this one?

**Comment by arieltian** [comment]
Looks good to me. I assume you tested the 2.5 api calls and also the change to the padding for one of the elements.

**Comment by elijahyoon** [comment]
Yup! I updated the response handling to match the 2.5 api response structure and updated the static weather data as well. Tested the app using the static data, DEV_API_KEY, and schema config field.

The padding change is very minor and only applied to the humidity but looked more centered for the handful of values I tested. Here are some examples:

Ex 1
Screenshot 2024-09-25 at 2 44 26 PM
Screenshot 2024-09-25 at 2 44 41 PM

Ex 2
Screenshot 2024-09-25 at 2 43 58 PM
Screenshot 2024-09-25 at 2 43 46 PM

Ex 3
Screenshot 2024-09-25 at 2 48 20 PM
Screenshot 2024-09-25 at 2 48 02 PM

**Comment by arieltian** [comment]
Great, ship it

**Pull request merged**
