### PR TITLE
Minnesota Light Rail App

### PR DESCRIPTION
**Pull request by AmillionAirs**
Guys I've got what you have all been waiting for A MINNESOTA LIGHT RAIL APP!! This simply has the user input the STOPID and Station Name from their local station which can easily be obtained from the metro transit website. I have the URL in the schema section so the user easily knows where to go to find station name and STOP ID.  The app then grabs depatrure time from the Metro transit API and displays that also along wiith the color of the train line and the 3 letter destination as well!

Fair warning i submitted this through the github Desktop App so if things are messed up please let me know. I'm trying it a different way this time as I learn the wonderful world of git! GIFS and pics attached so you know what this bad boy looks like!

image

a44e1bd9dcd272bc3f36a52e039b821812ef25b6

### CODE REVIEW

**Comment by AmillionAirs** [comment]
HI @betterengineering

**Comment by AmillionAirs** [comment]
Lint keeps failing, but build and test passed. Im sure its formatting related, but i cant for the life of me get buildifier to work on vscode? if you have any advice id greatly appreciate it.

**Comment by rohansingh** [comment]
Hi @AmillionAirs. Happy to help out with the lint. However, there's another issue we're going to have.

It looks like we're using the NexTrip version 1 API here, and that's going out of service very soon:

> NOTICE: NexTrip version 1 (https://svc.metrotransit.org/nextrip/) is deprecated and will be removed at the end of June '22.
>
> Version 2 documentation can be found at https://svc.metrotransit.org/swagger.

(from [svc.metrotransit.org](https://svc.metrotransit.org/))

Could you please switch to the V2 API?

**Review by rohansingh — CHANGES_REQUESTED** [review]
Hi @AmillionAirs. Happy to help out with the lint. However, there's another issue we're going to have.

It looks like we're using the NexTrip version 1 API here, and that's going out of service very soon:

> NOTICE: NexTrip version 1 (https://svc.metrotransit.org/nextrip/) is deprecated and will be removed at the end of June '22.
>
> Version 2 documentation can be found at https://svc.metrotransit.org/swagger.

(from [svc.metrotransit.org](https://svc.metrotransit.org/))

Could you please switch to the V2 API?

**Comment by AmillionAirs** [comment]
Alright sir i went ahead and updated all the calls for ya! let me know how that goes

**Comment by AmillionAirs** [comment]
O jeez i was messing around with a new app i made and i guess it committed that to this project? any chance we can just remove the countdown app stuff im not sure how to do that im so sorry.

**Review by AmillionAirs — COMMENTED** [review]
Added API changes as requested

**Comment by AmillionAirs** [comment]
TAKE THAT LINT!!!!

**Comment by rohansingh** [comment]
Great, merging now. I think a good improvement to add before a big release would be caching the data for at least 30 seconds.

**Review by rohansingh — APPROVED** [review]

**Pull request merged**
