### PR TITLE
Add de-DE and de-CH localizations for dutchfuzzyclock

### PR DESCRIPTION
**Pull request by IngmarStein**
# Description

dutchfuzzyclock already supports nl-NL, nl-BE, en-US, and en-GB locales. This pull request adds translations for de-DE and de-CH.

# Copilot

### Summary
🇩🇪🕒🗣️

This pull request extends the `dutch_fuzzy_clock` app to support German language and regional variations. It adds new data and logic for the de-DE and de-CH locales in the `dutch_fuzzy_clock.star` file.

> _`dutch_fuzzy_clock`_
> _adds German words and schema_
> _snowy winter time_

### Walkthrough
*  Add support for German fuzzy clock display in `dutch_fuzzy_clock.star` ([link](https://github.com/tidbyt/community/pull/1535/files?diff=unified&w=0#diff-e57a2b8c81874208fc6516529d189a94cd5d259014dec356657fcce8cb11e909R37-R51), [link](https://github.com/tidbyt/community/pull/1535/files?diff=unified&w=0#diff-e57a2b8c81874208fc6516529d189a94cd5d259014dec356657fcce8cb11e909R70), [link](https://github.com/tidbyt/community/pull/1535/files?diff=unified&w=0#diff-e57a2b8c81874208fc6516529d189a94cd5d259014dec356657fcce8cb11e909R85-R96), [link](https://github.com/tidbyt/community/pull/1535/files?diff=unified&w=0#diff-e57a2b8c81874208fc6516529d189a94cd5d259014dec356657fcce8cb11e909R187-R194), [link](https://github.com/tidbyt/community/pull/1535/files?diff=unified&w=0#diff-e57a2b8c81874208fc6516529d189a94cd5d259014dec356657fcce8cb11e909L181-R217))
  * Define dictionaries of German numbers and words for hour, half, to, and past for de-DE and de-CH locales ([link](https://github.com/tidbyt/community/pull/1535/files?diff=unified&w=0#diff-e57a2b8c81874208fc6516529d189a94cd5d259014dec356657fcce8cb11e909R37-R51), [link](https://github.com/tidbyt/community/pull/1535/files?diff=unified&w=0#diff-e57a2b8c81874208fc6516529d189a94cd5d259014dec356657fcce8cb11e909R70), [link](https://github.com/tidbyt/community/pull/1535/files?diff=unified&w=0#diff-e57a2b8c81874208fc6516529d189a94cd5d259014dec356657fcce8cb11e909R85-R96))
  * Add schema options for de-DE and de-CH locales in the settings menu ([link](https://github.com/tidbyt/community/pull/1535/files?diff=unified&w=0#diff-e57a2b8c81874208fc6516529d189a94cd5d259014dec356657fcce8cb11e909R187-R194))
  * Update description of the language setting to include German ([link](https://github.com/tidbyt/community/pull/1535/files?diff=unified&w=0#diff-e57a2b8c81874208fc6516529d189a94cd5d259014dec356657fcce8cb11e909L181-R217))

### CODE REVIEW

**Comment by IngmarStein** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by IngmarStein** [comment]
CC @remyblok as original author

**Comment by IngmarStein** [comment]
Friendly ping @matslina, @betterengineering

**Comment by matslina** [comment]
Thanks for the PR!

**Comment by IngmarStein** [comment]
Thanks for merging! I think `fuzzyclock` and `dutchfuzzyclock` should be merged, if the original authors agree.

**Comment by matslina** [comment]
I think I agree. If you're on our discord, that could be a good place to get that conversation going. Some help from our side will likely be needed to do migrate existing installations (and there are a lot of them out there; fuzzy clock is popular).

**Pull request merged**
