### PR TITLE
Emergency Bug Fixes!

### PR DESCRIPTION
**Pull request by JimAdkins**
Several users have reached out about issues experienced with the latest changes. Paul and I have been working on more gracefully falling back to previous api calls if v2 does not work, or does not have all of the required data to display.

### CODE REVIEW

**Comment by matslina** [comment]
@jer-tav cool to merge?

**Comment by IsThisPaul** [comment]
I have worked with Jim and tested this throughly. I think we're good to go.

**Comment by IsThisPaul** [comment]
> @jer-tav cool to merge?

@matslina Jer is not still involved with the dev of this app. I'm the main author and it's ready to merge

**Comment by JimAdkins** [comment]
@matslina just wanted to check in. @IsThisPaul said that Jer is no longer involved in the dev of this app. Do you need anything else from us to merge these nightscout.star bug fixes? 

Thanks!

**Comment by jer-tav** [comment]
Hey guys - I was just the initial author of the app, no need to run
anything by me.  You guys have made it way better than I ever could've!

**Comment by matslina** [comment]
Sorrry for the incorrect tagging! That's what happens when I try to review PRs from a cab.

**Pull request merged**
