### PR TITLE
Fix endpoint for retrieving lirr information

### PR DESCRIPTION
**Pull request by bralax**
# Description
This change fixes the LIRR app to use the latest data source. They swapped out their single large json with a zip containing 6 small csv files.

# Copilot

### Summary
🚅🗜️🧹

This pull request improves the LIRR app by switching to a better data source and streamlining the code. It uses the `zipfile` and `csv` modules to read and parse the GTFS ZIP feed, and removes some redundant functions from `lirr.star`.

> _Oh we're the crew of the LIRR_
> _And we sail on the rails of steel_
> _We've got a new ZIP feed for our GTFS_
> _And it makes our data more real_

### Walkthrough
* Import and use `zipfile` and `csv` modules to handle ZIP and CSV data from LIRR GTFS feed ([link](https://github.com/tidbyt/community/pull/1722/files?diff=unified&w=0#diff-b7861d758969783057321834900fcf6ae2a672936bbdcf13619e14318656de84R9-R10), [link](https://github.com/tidbyt/community/pull/1722/files?diff=unified&w=0#diff-b7861d758969783057321834900fcf6ae2a672936bbdcf13619e14318656de84L179-R184), [link](https://github.com/tidbyt/community/pull/1722/files?diff=unified&w=0#diff-b7861d758969783057321834900fcf6ae2a672936bbdcf13619e14318656de84L189-R234))
* Remove unnecessary functions to generate lists from GTFS data, use `convert_to_json_obj` instead ([link](https://github.com/tidbyt/community/pull/1722/files?diff=unified&w=0#diff-b7861d758969783057321834900fcf6ae2a672936bbdcf13619e14318656de84L235-L255))
* Print `stops` and `time_now` variables for debugging purposes ([link](https://github.com/tidbyt/community/pull/1722/files?diff=unified&w=0#diff-b7861d758969783057321834900fcf6ae2a672936bbdcf13619e14318656de84R33), [link](https://github.com/tidbyt/community/pull/1722/files?diff=unified&w=0#diff-b7861d758969783057321834900fcf6ae2a672936bbdcf13619e14318656de84R127))

### CODE REVIEW

**Comment by bralax** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by tavdog** [comment]
This app is still broken. This fix is needed I think.

**Comment by tavdog** [comment]
recheck

**Comment by bralax** [comment]
@betterengineering @matslina Would you be able to re-open this pull request? I don't have the permissions to do so.

**Comment by tavdog** [comment]
I tried doing my own PR with your changes @bralax but got this during check task `Problem: app failed to load: failed to load applet: starlark.ExecFile: cannot load compress/zipfile.star: invalid module: compress/zipfile.star`

**Comment by bralax** [comment]
It looks like the version of pixlet the checks use are out of date. The zipfile module was [added](https://github.com/tidbyt/pixlet/commit/d44879bdbd128d980abad2b02a24b211f1080623) on 7/31

**Pull request closed without merging**
