### PR TITLE
New app: Loterias (brazilian lottery)

### PR DESCRIPTION
**Pull request by danielsitnik**
# Description
The [Loteria](https://loterias.caixa.gov.br/) is the official Brazilian lottery. This app displays the estimated prize value and how much time you have left to bet until the next draw, for the various modalities of the loteria.

Example:
loterias

# Copilot

### Summary
➕🎟️🐛

This pull request adds a new app called Loterias, which shows lottery information for Brazil. It also updates the example code in `loterias.star` to include a new function and a module import, and fixes a mistake in the `addTwoNumbers` function. It also adds the required `manifest.yaml` and `README.md` files for the app.

> _`subtractTwoNumbers`_
> _A new function for Starlark_
> _Autumn leaves falling_

### Walkthrough
*  Add a new app called Loterias that displays lottery information for Brazil ([link](https://github.com/tidbyt/community/pull/1679/files?diff=unified&w=0#diff-ab4bfc4c21d9f17d2e3ac7076929ac7914ac936f22eb6e6d74f8260006ba4084R1-R8))
*  Create a `manifest.yaml` file to provide the app metadata and configuration ([link](https://github.com/tidbyt/community/pull/1679/files?diff=unified&w=0#diff-ab4bfc4c21d9f17d2e3ac7076929ac7914ac936f22eb6e6d74f8260006ba4084R1-R8))
*  Fix a logical error in the `addTwoNumbers` function in the example code in `README.md` ([link](https://github.com/tidbyt/community/pull/1679/files?diff=unified&w=0#diff-1dfe3fcb6a4b985674310627e39d3ea90a37a54fe51f85634cdd22cec5e51804R1-R46))
*  Add a new function `subtractTwoNumbers` to the example code in `loterias.star` and show how to use the `load` function to import modules ([link](https://github.com/tidbyt/community/pull/1679/files?diff=unified&w=0#diff-27478b44f0016a63d7cb108b2fcd040116b0e7298cec241626865b354fda6cd6R1-R250))

### CODE REVIEW

**Comment by danielsitnik** [comment]
Weird, the check that failed mentions a problem with a certificate when it ran pixlet check and hit the API used by the app:  `x509: certificate signed by unknown authority`.

It does work locally with pixlet check, pixlet render and pixlet serve. Also, the API is public, it has no authentication and is the same API that powers the public [loteria web portal](https://loterias.caixa.gov.br/).

Seems like a problem with the certificates used by Github Actions. 😕

**Comment by danielsitnik** [comment]
@betterengineering @matslina please, any inputs on this?

**Comment by danielsitnik** [comment]
@betterengineering or @matslina this build is still failing with some kind of certificate error.
It's been more than a week now, would you please take a look into it?

Thanks.

**Comment by rohansingh** [comment]
@danielsitnik I've taken a look and it appears that the SSL certificate on that domain is configured incorrectly. The presented cert is not trusted by the Mozilla root store, and no valid chain is being presented. It is trusted by some browsers, but not by our servers, or by the GitHub Actions containers where the tests run.

Checked with these tools and they all reported the same issue:
https://www.sslchecker.com/sslchecker
https://www.ssllabs.com/ssltest/analyze.html?d=servicebus2.caixa.gov.br
https://www.digicert.com/help/

**Comment by danielsitnik** [comment]
@rohansingh or @betterengineering I have fixed the problem with the certificate.
Can we move this forward or should I open a new PR?

Thanks!

**Pull request closed without merging**
