### PR TITLE
New App: Subreddit

### PR DESCRIPTION
**Pull request by fytpet**
Displays the #&#x2060;1 post of a given subreddit. Also displays the current time in a given timezone in either 24-hour or 12-hour format.

preview

### CODE REVIEW

**Comment by fytpet** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by rs7q5** [comment]
Is that time the current time or time of post? Looks like current time. Any chance for an option for time of the post?

**Comment by fytpet** [comment]
> Is that time the current time or time of post? Looks like current time. Any chance for an option for time of the post?

Great idea! I'll get working on that.

**Comment by rs7q5** [comment]
If there's room and it's in the same api call you may add number of comments and updoots (I mean upvotes).

**Review by betterengineering — APPROVED** [review]

**Pull request merged**
